---
permalink: api-changes.html 
sidebar: sidebar 
keywords: rest api, api changes, parameters, default values, breaking changes, documentation errors 
summary: NetAppは、主要な製品リリースごとにONTAP REST APIを継続的に強化および更新しています。これらの更新には、既存のAPI呼び出しの変更が含まれる場合があり、ONTAP機能へのアクセスが中断されることがあります。また、APIを使用する際には、他にも考慮すべき事項があり、ドキュメントにもいくつか誤りがあります。 
---
= ONTAP REST API呼び出しに対する変更点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、主要な製品リリースごとにONTAP REST APIを継続的に強化および更新しています。これらの更新には、既存のAPI呼び出しの変更が含まれる場合があり、ONTAP機能へのアクセスが中断されることがあります。また、APIを使用する際には、他にも考慮すべき事項があり、ドキュメントにもいくつか誤りがあります。



== 既存のONTAP REST API呼び出しに対する変更

エンドポイントやパラメータなど、既存の ONTAP REST API 呼び出しへの変更は、API を使用するソフトウェアに影響を与える可能性があります。ほとんどの場合、環境によっては、これらは_破壊的変更_とみなされます。下記の表のリストを確認して、自動化環境への影響があるかどうかを判断してください。各エントリには、該当する API エンドポイントまたは領域、変更の説明、および導入された ONTAP リリースが含まれています。

[cols="40%,50%,10%"]
|===
| APIエンドポイントまたは領域 | 動作の概要 | ONTAP リリース 


| Azure キーバックアップ | Azure Key Vault（AKV）の有効化と無効化に使用されるREST APIエンドポイントは、同期ではなく非同期で実行されるようになりました。これは、AKVを有効にするためのPOST操作と、無効にするためのDELETE操作に影響します。これらのAPI呼び出しを使用するクライアントは、非同期応答を処理するようにコードを更新する必要があります。これには、単なるHTTPステータスコードではなく、ジョブのステータスを確認することが含まれます。この変更は主に、ONTAP REST APIを通じてAzure Key Vault構成を管理するAzure NetApp Files（ANF）環境に影響します。 | 9.19.1 


| `/security/authentication/duo/groups`
`/security/authentication/duo/profiles` | 応答のフィールド*_links*は、これらのエンドポイントのデュオグループから削除されました。お客様による推奨されるアクションや回避策はありません。このフィールドは、ONTAPの今後のリリースで追加される予定です。 | 9.15.1 
|===


== REST API の使用に関するその他の考慮事項

破壊的または重大な変更に加えて、ONTAP REST API を使用する際に考慮すべき事項がいくつかあります。問題の種類は、新しいまたは代替の API 呼び出しの導入や ONTAP の内部処理の変更など多岐にわたります。各エントリには、該当する API エンドポイントまたは領域、動作の概要、および導入された ONTAP リリースが含まれます。

[cols="40%,50%,10%"]
|===
| APIエンドポイントまたは領域 | 動作の概要 | ONTAP リリース 


| `/api/application/containers` | コンテナを作成するために使用されるエンドポイントが強化され、以前は `/api/storage/volumes`を通じてのみ利用可能だったいくつかのボリューム構成パラメータがサポートされるようになりました。これにより、特にNetApp TridentをKubernetesストレージオーケストレーションに使用しているお客様は、永続ボリュームをプロビジョニングする際にONTAPのバランスのとれた配置機能を活用できます。ボリュームは、最適なパフォーマンスと容量利用率を実現するために、クラスタノード間で自動的に分散されます。ボリューム配置、QoSポリシー、または容量管理に関してきめ細かな制御が必要なコンテナ化されたアプリケーションをデプロイする場合は、更新されたエンドポイントを使用する必要があります。これは、ストレージリソース全体にわたる自動ロード バランシングが重要な大規模なKubernetes環境で特に役立ちます。 | 9.19.1 


| `/api/cluster/licensing/licenses` | 非常に大規模なONTAPクラスタ（32ノード以上）でREST APIを使用してライセンス情報を取得する場合、応答時間が遅くなることがあります。この問題は、System Managerのライセンスタブと、すべてのライセンスを同時に照会する自動ワークフローに影響します。影響を軽減するには、クエリパラメータを使用して特定の機能のライセンスを一度に1つずつ取得するか、単一のAPI呼び出しですべてのライセンスを取得する代わりに、コマンド `system license show`でCLIを使用できます。 | 9.19.1 
|===


== ONTAP REST APIリファレンスドキュメントのエラー

NetAppがONTAP REST APIを強化および更新すると、オンラインのリファレンスドキュメントにエラーが発生することがあります。これらのエラーは、APIの使用時に混乱を招く可能性がありますが、通常はONTAP自動化ソフトウェアまたは環境に影響を与えたり中断したりすることはありません。下記の表に記載されているエラー一覧を確認してください。これは、ONTAP REST APIリファレンスドキュメントをより深く理解し、活用するのに役立ちます。各エントリには、該当するAPIエンドポイントまたは領域、エラーの説明、およびそれが導入されたONTAPリリースが含まれています。

[cols="40%,50%,10%"]
|===
| APIエンドポイントまたは領域 | 変更の説明 | ONTAP リリース 


| `/storage/quota/reports` | エンドポイントのREST APIのドキュメントでは、*指定子*が有効なフィールドであることが示されています。ただし、このエンドポイントではクォータ指定子はサポートされません。お客様による推奨されるアクションや回避策はありません。このフィールドは、ONTAPの今後のリリースでAPIドキュメントから削除される予定です。 | 9.6 
|===
.関連情報
link:whats-new.html["ONTAP REST APIの新機能"]
