---
permalink: api-changes.html 
sidebar: sidebar 
keywords: rest api, api changes, parameters, default values, breaking changes, documentation errors 
summary: NetAppでは、製品のメジャーリリースごとにONTAP REST APIの拡張と更新を継続的に行っています。これらの更新には、パラメータや使用されているデフォルト値など、既存のAPI呼び出しに対する変更が含まれる場合があります。これらの変更は、REST APIにアクセスするソフトウェアに影響する可能性があります。 
---
= ONTAP REST API呼び出しに対する変更点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppでは、製品のメジャーリリースごとにONTAP REST APIの拡張と更新を継続的に行っています。これらの更新には、パラメータや使用されているデフォルト値など、既存のAPI呼び出しに対する変更が含まれる場合があります。これらの変更は、REST APIにアクセスするソフトウェアに影響する可能性があります。



== 既存のONTAP REST API呼び出しに対する変更

既存のAPI呼び出しに対する変更は、REST APIにアクセスするソフトウェアに影響する可能性があります。次の表の変更点を確認して、ONTAP自動化環境に影響がないかどうかを判断してください。各エントリには、該当するAPIエンドポイント、変更の説明、および導入されたONTAPリリースが含まれます。

[cols="40%,50%,10%"]
|===
| エンドポイント | 変更の説明 | ONTAP リリース 


| `/security/authentication/duo/groups`
`/security/authentication/duo/profiles` | 応答のフィールド*_links*は、これらのエンドポイントのデュオグループから削除されました。お客様による推奨されるアクションや回避策はありません。このフィールドは、ONTAPの今後のリリースで追加される予定です。 | 9.15.1 
|===


== ONTAP REST APIリファレンスドキュメントのエラー

NetAppはONTAP REST APIを拡張および更新するため、オンラインリファレンスドキュメントでエラーが発生することがあります。これらのエラーは、APIの使用時に混乱を招く可能性がありますが、通常はONTAP自動化ソフトウェアや環境に影響を与えたり、中断したりすることはありません。

次の表のエラーのリストを確認してください。これは、ONTAP REST APIのリファレンスドキュメントについて理解を深め、ナビゲートするのに役立ちます。各エントリには、該当するAPIエンドポイント、エラーの説明、およびAPIエンドポイントが導入されたONTAPリリースが含まれます。

[cols="40%,50%,10%"]
|===
| エンドポイント | 変更の説明 | ONTAP リリース 


| `/storage/quota/reports` | エンドポイントのREST APIのドキュメントでは、*指定子*が有効なフィールドであることが示されています。ただし、このエンドポイントではクォータ指定子はサポートされません。お客様による推奨されるアクションや回避策はありません。このフィールドは、ONTAPの今後のリリースでAPIドキュメントから削除される予定です。 | 9.6 
|===
.関連情報
link:whats-new.html["ONTAP REST APIの新機能"]
