---
sidebar: sidebar 
permalink: api_reference.html 
keywords:  
summary:  
---
= API リファレンス
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HTTP メソッド、入力パラメータ、応答など、すべての ONTAP REST API 呼び出しの詳細にアクセスできます。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。


NOTE: API リファレンスコンテンツには、ローカルの ONTAP システムまたはネットアップ開発者ネットワークの Web サイトからアクセスできます。



== ONTAP API ドキュメントページへのアクセス

[role="lead"]
ONTAP API オンラインドキュメントページは、ローカルの ONTAP システムからアクセスできます。

次の情報が必要です。

* ONTAP クラスタ管理 LIF の IP アドレスまたはホスト名
* ONTAP REST API にアクセスする権限を持つアカウントのユーザ名とパスワード


.手順
. ブラウザに URL を入力し、 *Enter* キーを押します。
+
https://<ip_address>/docs/api`

. ONTAP アカウントを使用してサインインします。
+
ONTAP API ドキュメントページが表示され、主要なリソースカテゴリ別に分類された API 呼び出しが下部に表示されます。

. 個々の API 呼び出しの例として、 * cluster * カテゴリまでスクロールし、 * get/cluster * をクリックします。




== NetApp DevNet でリファレンスコンテンツにアクセスする

[role="lead"]
ONTAP REST API リファレンスドキュメントは、ネットアップ開発者ネットワークの Web サイトから入手できます。

.手順
. ネットアップ開発者ネットワークの Web サイトで「 ONTAP REST API * 」ページに移動します。
+
https://devnet.netapp.com/restapi.php["ネットアップの DevNet ： ONTAP REST API"^]

. 下にスクロールし、 * オンライン REST API リファレンス * で該当する ONTAP バージョンのリンクをクリックします。
+
ONTAP API ドキュメントページが表示され、主要なリソースカテゴリ別に分類された API 呼び出しが下部に表示されます。

. 個々の API 呼び出しの例として、 * cluster * カテゴリまでスクロールし、 * get/cluster * をクリックします。

