---
sidebar: sidebar 
permalink: nas.html 
keywords:  
summary:  
---
= NAS
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラスタおよび SVM の CIFS と NFS の設定の管理に使用できる API 呼び出しを次に示します。



==== 監査ログのリダイレクト

NAS の監査イベントを特定の SVM にリダイレクトできます。このリソースタイプは ONTAP 9.8 で新たに追加されました。



==== 監査

SVM について、特定の CIFS イベントと NFS イベントをログに記録できます。この情報はセキュリティの向上に役立ちます。このリソースタイプは ONTAP 9.6 で導入されました。



==== CIFS ホームディレクトリ検索パス

CIFS サーバ上に SMB ユーザのホームディレクトリを作成すると、ユーザごとに個別の SMB 共有を作成する必要がなくなります。ホームディレクトリ検索パスは、 SVM のルートからの絶対パスのセットです。このリソースタイプは ONTAP 9.6 で導入されました。



==== CIFS サービス

CIFS サーバのコアの構成。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。



==== CIFS セッション数

この API を使用して、 CIFS セッションに関する詳細情報を取得できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で拡張されました。



==== CIFS 共有

CIFS サーバで定義されている SMB 共有。このリソースタイプは ONTAP 9.6 で導入されました。



==== CIFS 共有 ACL

CIFS 共有のフォルダおよびファイルへのアクセスを制御する Access Control List （ ACL ；アクセス制御リスト）。このリソースタイプは ONTAP 9.6 で導入されました。



==== CIFS UNIX シンボリックリンクマッピング

CIFS クライアントと UNIX クライアントの両方から同じデータストアにアクセスできます。UNIX クライアントでシンボリックリンクを作成した場合、これらのマッピングによって、 CIFS クライアント用に別のファイルまたはフォルダへの参照が提供されます。このリソースタイプは ONTAP 9.6 で導入されました。



==== ファイルアクセスのトレース

特定のファイルへのアクセスをトレースするために使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.8 で新たに追加されました。



==== ファイルセキュリティ権限

これらの API 呼び出しは、特定のファイルまたはフォルダに対して Windows ユーザまたは UNIX ユーザに付与されている有効な権限を表示します。NTFS ファイルセキュリティと監査ポリシーも管理できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で大幅に拡張されました。



==== FPolicy の

FPolicy は、 SVM でファイルアクセスイベントの監視と管理に使用されるファイルアクセス通知フレームワークです。このリソースタイプは ONTAP 9.6 で導入されました。



==== FPolicy エンジン

FPolicy エンジンを使用すると、ファイルアクセス通知を受信する外部サーバを識別できます。このリソースタイプは ONTAP 9.6 で導入されました。



==== FPolicy イベント

ファイルアクセスの監視方法と生成されるイベントを識別する構成。このリソースタイプは ONTAP 9.6 で導入されました。



==== FPolicy ポリシー

FPolicy エンジンやイベントなど、 FPolicy フレームワークの要素を格納するコンテナ。このリソースタイプは ONTAP 9.6 で導入されました。



==== NFS 接続クライアント

接続されているクライアントとその接続の詳細のリストを表示できます。このリソースタイプは ONTAP 9.7 で導入されました。



==== NFS エクスポートポリシー

NFS エクスポートに関するルールを含むポリシー。このリソースタイプは ONTAP 9.6 で導入されました。



==== NFS Kerberos インターフェイス

Kerberos のインターフェイスの設定。このリソースタイプは ONTAP 9.6 で導入されました。



==== NFS Kerberos Realm に移動します

Kerberos Realm の設定。このリソースタイプは ONTAP 9.6 で導入されました。



==== NFS サービス

NFS サーバのコアの構成。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。



==== vscan

ウイルスやその他の悪意のあるコードからデータを保護するセキュリティ機能。このリソースタイプは ONTAP 9.6 で導入されました。



==== Vscan オンアクセスポリシー

ファイルオブジェクトをクライアントからのアクセス時にアクティブにスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。



==== Vscan オンデマンドポリシー

ファイルオブジェクトをオンデマンドで即座にスキャンするか設定されたスケジュールに従ってスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。



==== Vscan スキャナプール

ONTAP と外部ウィルススキャンサーバの間の接続を管理するために使用される一連の属性。このリソースタイプは ONTAP 9.6 で導入されました。



==== Vscan サーバステータス

外部ウィルススキャンサーバのステータス。このリソースタイプは ONTAP 9.6 で導入されました。
