---
sidebar: sidebar 
permalink: networking.html 
keywords:  
summary:  
---
= ネットワーキング
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラスタで使用される物理ネットワークリソースと論理ネットワークリソースの管理に使用できる API 呼び出しを次に示します。



==== イーサネットブロードキャストドメイン

イーサネットブロードキャストドメインは、同じ物理ネットワークの一部として認識される物理ポートのセットです。ドメイン内のいずれかのポートからパケットがブロードキャストされると、すべてのポートがパケットを受信します。各ブロードキャストドメインは IPspace の一部です。このリソースタイプは ONTAP 9.6 で導入されました。



==== イーサネットポート

イーサネットポートは、物理ネットワークまたは仮想ネットワークのエンドポイントです。Link Aggregate Group （ LAG ；リンクアグリゲートグループ）に結合することも、 Virtual LAN （ VLAN ；仮想 LAN ）を使用して分離することもできます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。



==== イーサネット・スイッチ・ポート

イーサネットスイッチのポート情報を取得することができます。このリソースタイプは ONTAP 9.8 で新たに追加されました。



==== イーサネットスイッチ

ONTAP クラスタまたはストレージネットワークに使用されるイーサネットスイッチの設定を取得または変更できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。



==== Fibre Channel インターフェイス

Fibre Channel インターフェイスは、 SVM に関連付けられた論理エンドポイントです。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。



==== Fibre Channel ポート

Fibre Channel ポートは、 Fibre Channel ネットワークへの接続に使用される ONTAP ノード上の物理アダプタです。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。



==== HTTP プロキシ

SVM またはクラスタ IPspace の HTTP プロキシを設定できます。このリソースタイプは ONTAP 9.7 で導入されました。



==== BGP ピアグループ

Border Gateway Protocol ピアグループを作成および管理できます。このリソースタイプは ONTAP 9.7 で導入されました。



==== IP インターフェイス

Logical Interface （ LIF ；論理インターフェイス）は、追加の構成属性を持つ IP アドレスです。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。



==== IP ルート

ルーティングテーブルは、トラフィックを宛先に転送するために使用される IP ルートの集合です。このリソースタイプは ONTAP 9.6 で導入されました。



==== IP のサービスポリシー

IP サービスポリシーは、特定の LIF で使用可能なサービスを定義します。サービスポリシーは SVM または IPspace のコンテキストで設定できます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。



==== IPspace

IPspace は、 1 つ以上の SVM をサポートするためのネットワークスペースを作成します。IPspace を相互に分離することで、セキュリティとプライバシーが確保されます。このリソースタイプは ONTAP 9.6 で導入されました。
