---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  entries:
  - title: ONTAP 自動化に関するドキュメント
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: additional
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: リリースノート
      url: "/rn/whats_new.html"
    - title: ONTAP の自動化オプション
      url: "/get-started/ontap_automation_options.html"
    - title: REST API を使用するための準備を行う
      url: "/get-started/prepare.html"
    - title: Hello world
      url: "/get-started/hello_world.html"
  - title: ONTAP REST API
    links:
    - title: REST の実装の詳細
      url: "/rest/rest_web_services_foundation.html"
    - title: その他の考慮事項については
      url: "/rest/object_references_and_access.html"
    - title: REST リソースの概要
      url: "/resources/overview_categories.html"
    - title: API リファレンス
      url: "/reference/api_reference.html"
  - title: 自動化
    links:
    - title: Python クライアントライブラリ
      url: "/python/overview_pcl.html"
    - title: ONTAP と Ansible
      url: "/automate/ontap_ansible.html"
    - title: 自動化ブログ
      url: "/automate/blogs.html"
  - title: リソースの追加
    links:
    - title: 詳細はこちらをご覧ください
      url: "/additional/get_more_information.html"
    - title: ネットアップの DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 のドキュメント
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select のドキュメント
      url: https://docs.netapp.com/us-en/ontap-select/
