---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP 自動化に関するドキュメント
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: リリースノート
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: ONTAP の自動化オプション
      url: "/get-started/ontap_automation_options.html"
    - title: 最初のAPI呼び出し
      url: "/get-started/first_call.html"
  - title: ONTAP REST API
    links:
    - title: REST の実装の詳細
      url: "/rest/rest_web_services_foundation.html"
    - title: その他の考慮事項については
      url: "/rest/object_references_and_access.html"
    - title: RESTリソースの概要
      url: "/resources/overview_categories.html"
    - title: API リファレンス
      url: "/reference/api_reference.html"
  - title: 自動化
    links:
    - title: Python クライアントライブラリ
      url: "/python/overview_pcl.html"
    - title: ONTAP と Ansible
      url: "/automate/ontap_ansible.html"
    - title: 自動化ブログ
      url: "/automate/blogs.html"
  - title: REST APIに移行する
    links:
    - title: ONTAPI無効化
      url: "/migrate/overview.html"
    - title: ONTAPIからRESTへのマッピング
      url: "/migrate/mapping.html"
    - title: パフォーマンスカウンタ
      url: "/migrate/performance-counters.html"
    - title: ブログ記事
      url: "/migrate/blogs.html"
  - title: 知識とサポート
    links:
    - title: その他のリソース
      url: "/additional/resources.html"
    - title: ネットアップの DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 のドキュメント
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select のドキュメント
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: すべてのONTAP 製品ドキュメント
