---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: ONTAPのリリースごとにONTAP REST APIが更新され、新機能や機能拡張、バグの修正が行われます。 
---
= ONTAP REST APIの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAPのリリースごとにONTAP REST APIが更新され、新機能や機能拡張、バグの修正が行われます。


TIP: 既知の制限事項や問題などの追加情報については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP リリースノート"^]。また、自動化ソフトウェアに影響する可能性のある変更についても、を参照してください link:api-changes.html["ONTAP REST API呼び出しに対する変更点"] 。



== ONTAP 9.18.1

ONTAP 9.18.1 リリースでは、11 個の新しい API 呼び出しにより、 ONTAP REST API の機能が引き続き拡張されています。機能強化は主にセキュリティに重点を置いていますが、ストレージ管理に関連する改善も含まれます。

セキュリティ:: ONTAP 9.18.1 REST API では、2 つの主要なセキュリティ強化が導入されました。新しいクラスター ネットワーク API エンドポイントを使用して、クラスター ネットワークのセキュリティ構成を表示および更新できます。クラスター ネットワークでの証明書管理のための強力なサポートが組み込まれています。さらに、NVLog トラフィックの HA ネットワークのセキュリティ構成を表示および更新することもできます。
ストレージ:: NetApp FlexCacheは、元のボリュームの永続キャッシュです。ファンアウトをサポートしているため、単一の元のボリュームから複数のFlexCache を作成できます。  REST API には、キャッシュ インスタンスと元のボリューム間の接続ステータスの取得のサポートが含まれています。




== ONTAP 9.17.1

ONTAP 9.17.1リリースでは、約20個の新しいAPI呼び出しが追加され、 ONTAP REST APIの機能が引き続き拡張されています。このリリースでは、メディエーター処理、NMVeサブシステム、アプリケーションコンテナへの追加アップデートに加え、主にセキュリティ強化に重点を置いています。

セキュリティ:: ONTAP 9.17.1 REST APIでは、4つの主要なセキュリティ機能が導入されました。ONTAPのジャストインタイム（JIT）権限昇格は、ロールベースアクセス制御（RBAC）の拡張機能です。クラスタ管理者は、特権コマンドへのアクセスを許可する既存のロールへの一時的な昇格を要求できます。この機能には、堅牢な設定オプションが含まれています。OpenStackBarbicanキーマネージャのサポートが追加されました。このKMSは、 NetApp Volume Encryption（NVE）のキーを管理するために使用されます。ONTAP9.17.1には、SANボリューム向けの自律ランサムウェア保護（ARP）が含まれています。詳細なARPエントロピー統計は、REST APIを通じて入手できます。また、クラスタのSAMLデフォルトメタデータ設定を管理するためのAPI呼び出しもいくつか追加されました。
クラスターメディエーター:: ONTAP REST API を使用して、 NetAppコンソール クラウド サービスに ping を実行できます。また、既存のエンドポイントでPATCHメソッドを使用して、特定のメディエーターの設定を変更することもできます。
NVMe:: NVMeサブシステムは、NVMe接続されたホスト群の設定状態とネームスペースのアクセス制御を維持します。ONTAPONTAPでは、既存のエンドポイントを使用してPATCHメソッドを使用してNVMeサブシステムを変更できます。
アプリケーションコンテナ:: アプリケーションコンテナはONTAP 9.17.1の新機能であり、1つ以上のストレージオブジェクトのプロビジョニングを可能にします。クライアントのストレージアクセスに必要なポリシーとルールを設定できます。FlexCacheFlexCacheもプロビジョニング可能です。




== ONTAP 9 .16.1

ONTAP 9 .16.1には、20を超える新しいAPI呼び出しが含まれており、ONTAP REST APIの機能が引き続き拡張されています。これらの機能強化は主にセキュリティに重点が置かれていますが、指標とバケット管理の改善も含まれています。


NOTE: NetApp ASA R2システム（ASA A1K、ASA A70、およびASA A90）のユーザ向けに公開されるONTAP REST APIは、他のすべてのFAS、AFF、およびASAシステムで提供されるREST APIとは異なります。詳細については、を参照してください https://docs.netapp.com/us-en/asa-r2/learn-more/rest-api-support.html["ASA R2システムでのREST APIのサポート"^] 。

Microsoft Entra IDに対するOAuth 2.0のサポート:: OAuth 2.0のサポートは、ONTAP 9 14.1で最初に導入されました。OAuth 2.0の機能は、ONTAP 9 .16.1で強化され、標準のOAuth 2.0要求を持つMicrosoft Entra ID認証サーバー(旧Azure AD)をサポートします。次の2つの主な機能が含まれています。
グループをUUIDとして使用するOAuth 2.0:: UUIDスタイル値に基づくEntra ID標準グループ要求は、次の2つの新しい機能と10の新しいAPI呼び出しによってサポートされています。
+
--
* グループUUIDからグループ名(`/security/groups`へのマッピング）
* UUIDグループとロールのマッピング(`/security/group/role-mapping`）


--
外部ロールを使用するOAuth 2.0:: 外部ロールは、ONTAPに定義されたOAuth 2.0 Identifyプロバイダーで定義されます。これらの外部ロールとONTAPロール間のマッピング関係を作成および管理できます。5つの新しいAPI呼び出しが追加されました。
Web認証:: Web認証（WebAuthn）は、公開鍵暗号に基づいてユーザを安全に認証するためのWeb標準です。ONTAPでは、System ManagerおよびONTAP REST APIを使用して、フィッシングに強いMFAの管理をサポートしています。いくつかのエンドポイントに7つの新しいAPI呼び出しが追加されました。
自律型ランサムウェア対策のバージョン管理と更新:: ONTAPで使用されるAutonomous Ransomware Protectionパッケージを管理するための2つのAPI呼び出しが新しいエンドポイントに追加されました。Autonomous Ransomware Protectionパッケージのバージョンを表示して更新できます。
qtreeの指標:: ONTAP 9 .16.1には、オプションのqtree拡張パフォーマンス監視機能が含まれています。この機能を有効にすると、ONTAPはレイテンシの指標や履歴データを含む追加データをキャプチャします。このパフォーマンスデータを取得するための新しいエンドポイントが追加されました。
S3ハケツトノSnapshot:: S3バケットのSnapshotを作成および管理できるように、4つの新しいAPI呼び出しが追加されました。各Snapshotは、Snapshot作成時のバケットのイメージです。




== ONTAP 9.15.1

ONTAP 9 .15.1では、2つの新機能のサポートを含め、ONTAP REST APIの機能が引き続き拡張されています。

TLS経由のNFS:: この機能では、3つの新しいエンドポイントを使用できます。これらのAPI呼び出しを問題して、すべてのNFS over TLSインターフェイスの取得、UUIDによる特定のインターフェイスの取得、およびTLSインターフェイスの設定プロパティの更新を行うことができます。これらのAPI呼び出しをまとめて使用すると、 `vserver nfs tls interface` CLIコマンド。



CAUTION: ONTAP 9.15.1では、NFS over TLSがパブリックプレビューとして提供されています。プレビュー版として、この機能はONTAP 9.15.1の本番環境ワークロードではサポートされていません。

WindowsバックアップアプリケーションとUNIX形式のシンボリックリンク:: WindowsバックアップアプリケーションでUNIX形式のシンボリックリンク（symlink）が検出されると、リンクがトラバースされ、データがONTAPから返されてバックアップされます。ONTAP 9.15.1以降では、シンボリックリンクが指すデータではなくシンボリックリンクをバックアップするオプションも用意されています。これにより、バックアップアプリケーションのパフォーマンスの向上など、いくつかの利点が得られます。エンドポイント `/protocols/cifs/services/{svm.uuid}` が更新され、新しいパラメータがオブジェクトに追加され `backup-symlink-enabled` `options` ました。




== ONTAP 9.14.1

ONTAP 9.14.1リリースには、30以上の新しいAPI呼び出しが含まれており、引き続きONTAP REST APIの機能が拡張されています。これらのエンドポイントは、既存の機能の更新に加えて、いくつかの新しいONTAP機能をサポートします。このリリースでは、主にセキュリティの強化に重点を置いていますが、NAS、QoS、パフォーマンス指標の改善も含まれています。

セキュリティ:: ONTAP 9.14.1で導入された2つの主要なセキュリティ機能があります。Open Authorization（OAuth 2.0）は、ONTAPストレージリソースへのアクセスを制限するために使用できるトークンベースのフレームワークです。REST APIを使用してONTAPにアクセスするクライアントで使用できます。設定は、REST APIを含む任意のONTAP管理インターフェイスを使用して実行できます。ONTAP 9.14.1リリースでは、SSHログインの2要素認証を提供するCisco Duoもサポートされています。Duoは、ONTAPクラスタレベルまたはSVMレベルで動作するように設定できます。これら2つの新機能に加えて、いくつかのエンドポイントが追加され、キーストアの制御が向上しました。
FPolicyの永続的ストレージ:: FPolicyは、ONTAPポリシーを管理するためのプラットフォームを提供します。イベントやポリシーエンジンなど、さまざまなコンポーネントや要素のコンテナを提供します。REST APIを使用して、ONTAP FPolicyの設定およびイベント用の永続的ストアを設定および管理できるようになりました。SVMごとに1つの永続的ストアを設定でき、SVM内の複数のポリシーで共有されます。
QoSオプション:: クラスタのQoSオプションを取得および設定できるように、2つのエンドポイントが導入されました。たとえば、バックグラウンドタスク用に使用可能なシステム処理リソースの割合を予約できます。
パフォーマンス指標:: ONTAPは、システムの動作特性に関する統計情報を保持します。この情報は、テーブルと行で構成されるデータベース形式で表示されます。ONTAP 9.14.1では、ファイバチャネル、iSCSI、LUN、NVMeなど、複数のリソースカテゴリで指標データが追加されました。この追加の指標データにより、ONTAP REST APIは引き続きData ONTAP API（ONTAPIまたはZAPI）と同等になります。
その他の機能拡張:: 使用する環境に応じて、さらにいくつかの拡張機能が追加されています。これらの新しいエンドポイントを使用すると、SANイニシエータへのアクセスとホストキャッシュ設定の制御が向上し、個 々 のAutoSupportメッセージにアクセスできるようになります。




== ONTAP 9.13.1

ONTAP 9.13.1では、20を超える新しいAPI呼び出しが追加され、引き続きONTAP REST APIの機能が拡張されています。これらのエンドポイントは、ONTAP の新しい機能および既存の機能拡張をサポートします。このリリースでは、セキュリティ、リソース管理、強化されたSVM設定オプション、パフォーマンス指標の改善に重点が置かれています。

リソースタギング:: タグを使用してREST APIリソースをグループ化できます。これは、特定のプロジェクトまたは組織グループ内の関連リソースを関連付ける場合に行います。タグを使用すると、リソースをより効果的に整理および追跡できます。
整合グループ:: ONTAP 9.13.1では、パフォーマンスカウンタデータの可用性が引き続き拡張されています。この種の統計情報にアクセスして、整合性グループのパフォーマンスと容量の履歴を追跡できるようになりました。さらに、コンシステンシグループ間の親子関係を設定および管理できるように拡張されました。
SVMごとのDNS設定:: 既存のDNSエンドポイントが拡張され、DNSドメインとサーバの設定を個 々 のSVMに対して実行できるようになりました。
EMSロールの設定:: 既存のEMSサポート機能が拡張され、ロールとロールに割り当てられたアクセス制御設定を管理できるようになりました。これにより、ロールの設定に基づいてイベントやメッセージを制限またはフィルタリングできます。
セキュリティ:: REST APIを使用して、サインインしてSSHを使用してONTAP にアクセスするアカウントの時間ベースのワンタイムパスワード（TOTP）プロファイルを設定できます。また、キー管理エンドポイントが拡張され、指定したキー管理サーバからのリストア処理が可能になりました。
SVMごとのCIFS設定:: 既存のCIFSエンドポイントが拡張され、特定のSVMの設定を更新できるようになりました。
S3バケットルール:: 既存のS3バケットエンドポイントが拡張されてルール定義が追加されました。各ルールはリストオブジェクトであり、バケット内のオブジェクトに対して実行される一連のアクションを定義します。これらのルールをまとめて使用することで、S3バケットのライフサイクルをより適切に管理できます。




== ONTAP 9.12.1

ONTAP 9.12.1では、40以上の新しいAPI呼び出しによって、ONTAP REST APIの機能が拡張されています。これらのエンドポイントは、ONTAP の新しい機能および既存の機能拡張をサポートします。このリリースでは、セキュリティ機能とNAS機能の強化に焦点を当てています。

セキュリティの機能拡張:: Amazon Web Servicesには、キーなどのシークレット用のセキュアなストレージを提供するキー管理サービスが含まれています。このサービスにはREST APIからアクセスできます。これにより、ONTAP は暗号化キーをクラウドにセキュアに格納できます。また、NetApp Storage Encryptionで使用する認証キーを作成して一覧表示することもできます。
Active Directory:: ONTAP クラスタ用に定義されたActive Directoryアカウントを管理できます。これには、新しいアカウントの作成、アカウントの表示、更新、削除などが含まれます。
CIFSグループポリシー:: REST APIが強化され、CIFSグループポリシーの作成と管理がサポートされるようになりました。設定情報は、すべてまたは特定のSVMに適用されるグループポリシーオブジェクトによって提供および管理されます。




== ONTAP 9.11.1

ONTAP 9.11.1では、引き続きONTAP REST APIの機能が拡張され、約100件の新しいAPI呼び出しが追加されています。これらのエンドポイントは、新しいONTAP 機能および既存の機能拡張をサポートします。

きめ細かなRBAC:: ONTAP のRole-Based Access Control（RBAC；ロールベースアクセス制御）機能が強化され、さらに細かくアクセスを制御できるようになりました。REST APIを使用すると、従来のロールを使用したり、必要に応じて新しいカスタムロールを作成したりできます。各ロールには1つ以上の権限が関連付けられます。それぞれの権限は、REST API呼び出しまたはCLIコマンドとアクセスレベルを識別します。RESTロールでは、次のような新しいアクセスレベルを使用できます。 `read_create` および `read_modify`。この拡張機能は、Data ONTAP API（ONTAPIまたはZAPI）と同じ機能を提供し、REST APIへのユーザの移行をサポートします。を参照してください link:rest/rbac_overview.html["RBAC セキュリティ"] を参照してください。
パフォーマンスカウンタ:: ONTAP の以前のリリースでは、システムの動作特性に関する統計情報が管理されていました。9.11.1リリースでは、この情報が拡張され、REST APIから使用できるようになりました。管理者または自動プロセスは、データにアクセスしてシステムのパフォーマンスを判断できます。カウンタマネージャサブシステムが管理する統計情報は、テーブルと行を使用してデータベース形式で表示されます。この拡張機能により、ONTAP REST APIはData ONTAP API（ONTAPIまたはZAPI）と同等に機能します。
アグリゲートの管理:: ONTAP ストレージアグリゲートの管理が強化されました。更新されたRESTエンドポイントを使用して、アグリゲートをオンラインとオフラインに切り替えたり、スペアを管理したりできます。
IPサブネット機能:: ONTAP のネットワーク機能が拡張され、IPサブネットのサポートが追加されました。REST APIを使用すると、ONTAP クラスタ内のIPサブネットの設定と管理にアクセスできます。
複数の管理者の検証:: 複数の管理者による検証機能は、ONTAP のコマンドや操作へのアクセスを保護するための柔軟な認証フレームワークを提供します。制限されたコマンドを識別するルールを定義できます。ユーザから特定のコマンドへのアクセスが要求された場合、必要に応じて、複数のONTAP 管理者に承認を与えることができます。
SnapMirrorの機能拡張:: SnapMirror機能は、スケジュール設定など、いくつかの領域で強化されています。ONTAP 9.11.1のDP関係にSnapVault 関係のパリティも追加され、REST APIで使用できるスロットル機能は、Data ONTAP API（ONTAPIまたはZAPI）と同じ値に達しています。これに関連して、Snapshotコピーの一括作成と管理がサポートされます。
ストレージプール:: ONTAP ストレージプールへのアクセスを提供するためにいくつかのエンドポイントが追加されています。クラスタ内のストレージプールの作成および一覧表示、特定のプールのIDによる更新および削除がサポートされます。
ネームサービスキャッシュのサポート:: ONTAP ネームサービスが強化され、キャッシュがサポートされるようになり、パフォーマンスと耐障害性が向上しています。REST APIを使用してネームサービスキャッシュの設定にアクセスできるようになりました。設定は、ホスト、UNIXユーザ、UNIXグループ、ネットグループなど、複数のレベルで適用できます。
ONTAPIレポートツール:: ONTAPIレポートツールを使用すると、お客様やパートナー様が自社の環境でONTAPIを使用する状況を特定する際に役立ちます。このツールは、ONTAPIからONTAP REST APIへの移行を計画しているお客様にとって有益な分析情報を提供します。




== ONTAP 9.10.1

ONTAP 9.10.1 では、引き続き ONTAP REST API の機能が拡張されています。ONTAP の新機能と既存の機能拡張をサポートするために、 100 以上の新しいエンドポイントが追加されています。次に、 REST API の拡張機能の概要を示します。

アプリケーション整合グループ:: 整合グループは、 Snapshot などの特定の処理を実行するときにグループ化される一連のボリュームです。この機能は、単一ボリュームの操作時に、クラッシュ整合性とデータ整合性を暗黙的に拡張したものです。大規模なマルチボリュームワークロードアプリケーションに有効です。
SVM 移行:: SVM は、ソースクラスタからデスティネーションクラスタに移行できます。新しいエンドポイントは、一時停止、再開、ステータスの読み出し、移行処理の中止など、すべての機能を制御します。
ファイルのクローニングと管理:: ボリュームレベルのファイルクローニングと管理が強化されました。新しい REST エンドポイントでは、ファイルの移動、コピー、およびスプリットの処理がサポートされます。
S3 監査の強化:: S3 イベントの監査は、セキュリティの向上によって特定の S3 イベントを追跡してログに記録できるようになりました。S3 監査イベントセレクタは、バケット単位で SVM 単位で設定できます。
ランサムウェア防御:: ONTAP は、ランサムウェアの脅威を含む可能性のあるファイルを検出しますこれらの疑わしいファイルのリストを取得したり、ボリュームから削除したりできます。
その他のセキュリティ機能強化:: 既存のプロトコルを拡張し、新しい機能を導入するための一般的なセキュリティ機能がいくつか強化されています。IPSec 、キー管理、 SSH 設定、およびファイル権限が改善されました。
CIFS ドメインおよびローカルグループ:: クラスタレベルおよび SVM レベルで CIFS ドメインのサポートが追加されました。ドメイン設定を取得したり、優先ドメインコントローラを作成および削除したりできます。
ボリューム分析を強化:: 上位のファイル、ディレクトリ、ユーザをサポートするために、追加のエンドポイントを通じてボリューム分析と指標が拡張されました。
サポートの強化:: サポートは、いくつかの新機能によって強化されています。自動アップデートでは、最新のソフトウェアアップデートをダウンロードして適用することで、ONTAPシステムを最新の状態に保つことができます。ノードによって生成されたメモリコアダンプを取得および管理することもできます。




== ONTAP 9.9.1

ONTAP 9.9.1 では、引き続き ONTAP REST API の機能が拡張されています。SAN ポートセットや vServer ファイルディレクトリのセキュリティなど、既存の ONTAP 機能用の新しい API エンドポイントが追加されました。また、 ONTAP 9.9.1 の新しい機能と機能拡張をサポートするためにエンドポイントが追加されました。関連ドキュメントも改善されています。拡張機能の概要を以下に示します。

ONTAPI を ONTAP 9 REST API にマッピングしています:: ONTAP 自動化コードを REST API に移行するために、ネットアップでは API マッピングのドキュメントを提供しています。このリファレンスには、 ONTAPI コールのリストと、それぞれの REST API に相当する機能が含まれます。マッピングドキュメントが更新され、 ONTAP 9.9.1 の新しい API エンドポイントが追加されました。を参照してください link:migrate/mapping.html["ONTAPI から REST API へのマッピング"] を参照してください。
ONTAP 9.9.1 の新しいコア機能用の API エンドポイント:: ONTAPI API では使用できない ONTAP 9.9.1 の新しい機能のサポートが REST API に追加されました。ネストされた igroup と Google Cloud Key Management Services もサポートされます。
ONTAPI から REST への移行のサポートが改善されました:: 以前の ONTAPI コールのうち、対応する REST API に相当するものが追加されました。これには、ローカル UNIX ユーザとグループ、クライアント、 SAN ポートセット、ボリュームスペース属性を必要とせずに NTFS ファイルセキュリティを管理する作業が含まれます。これらの変更は、更新された ONTAPI から REST へのマッピングのドキュメントにも含まれます。
オンラインドキュメントが強化されました:: ONTAP オンラインドキュメントのリファレンスページに、 ONTAP 9.9..1 で新たに追加されたものも含め、各 REST エンドポイントまたはパラメータが導入されたときの ONTAP リリースを示すラベルが追加されました。




== ONTAP 9.8

ONTAP 9 .8には、ONTAPストレージシステムの導入と管理を自動化する機能を強化するいくつかの新機能が含まれています。また、従来のONTAPI API APIからRESTへの移行を支援するためのサポートが強化されています。

ONTAPI を ONTAP 9 REST API にマッピングしています:: ONTAPI の自動化を更新するのに役立つように、 1 つ以上の入力パラメータを必要とする ONTAPI コールのリストと、それに相当する ONTAP 9 の REST API コールへのマッピングが提供されます。を参照してください link:migrate/mapping.html["ONTAPI から REST API へのマッピング"] を参照してください。
ONTAP 9 .8の新しい機能のAPIエンドポイント:: ONTAPIでは使用できない新しいONTAP 9 .8機能がREST APIでサポートされるようになりました。これには、ONTAP S3のバケットとサービスのREST APIサポート、SnapMirror Active Sync（旧SnapMirrorビジネス継続性）、ファイルシステム分析が含まれます。
セキュリティ強化のための拡張サポート:: セキュリティは、 Azure Key Vault 、 Google Cloud Key Management Services 、 IPSec 、証明書署名要求などの複数のサービスとプロトコルをサポートすることで強化されています。
簡易性を向上するための機能拡張:: ONTAP 9.8 では、 REST API を使用して、より効率的で最新のワークフローを実現できます。たとえば、ワンクリックでファームウェアのアップデートを複数の種類のファームウェアで利用できるようになりました。
オンラインドキュメントが強化されました:: ONTAPオンラインドキュメントページには、9.8の新機能を含む、各RESTエンドポイントまたはパラメータが導入されたONTAPリリースを示すラベルが含まれています。
ONTAPI から REST への移行のサポートが改善されました:: 以前の ONTAPI コールに対応する REST API に相当する機能が追加されました。既存の ONTAPI コールの代わりに使用する REST エンドポイントを特定する方法については、ドキュメントでも説明しています。
パフォーマンス指標の強化:: REST API のパフォーマンス指標が拡張され、いくつかの新しいストレージオブジェクトとネットワークオブジェクトが追加されました。




== ONTAP 9.7

ONTAP 9.7 では、 ONTAP REST API の機能を拡張するために、以下の 3 つの新しいリソースカテゴリが追加されています。それぞれに複数の REST エンドポイントが含まれています。

* NDMP
* オブジェクトストア
* SnapLock


ONTAP 9.7 では、既存のいくつかのリソースカテゴリに 1 つ以上の新しい REST エンドポイントが導入されています。

* クラスタ
* NAS
* ネットワーキング
* NVMe
* SAN
* セキュリティ
* ストレージ
* サポート




== ONTAP 9.6

ONTAP 9.6 は、 ONTAP 9.4 で導入された REST API のサポートを大幅に拡張します。ONTAP 9.6 REST API は、ほとんどの ONTAP 設定タスクおよび管理タスクをサポートします。

ONTAP 9.6 の REST API には、次のような重要な領域などがあります。

* クラスタセットアップ
* プロトコルの設定
* プロビジョニング
* パフォーマンスの監視
* データ保護
* アプリケーション対応のデータ管理

