---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= ONTAP REST API と自動化の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ネットアップでは、 ONTAP REST API を定期的に更新して、新機能、拡張機能、およびバグ修正を提供しています。



== ONTAP 9.11.1

ONTAP 9.11.1では、引き続きONTAP REST APIの機能が拡張され、約100件の新しいAPI呼び出しが追加されています。これらのエンドポイントは、新しいONTAP 機能および既存の機能拡張をサポートします。このリリースでは、Data ONTAP API（ONTAPIまたはZAPI）からONTAP REST APIへのお客様の移行をサポートすることに焦点を当てています。

きめ細かなRBAC:: ONTAP のRole-Based Access Control（RBAC；ロールベースアクセス制御）機能が強化され、さらに細かくアクセスを制御できるようになりました。必要に応じて、従来のロールを使用したり、新しいロールを作成したりできます。各ロールには1つ以上のアクセス定義を関連付けることができます。それぞれのアクセス定義は、コマンドまたはREST API呼び出しと、アクセスレベルの要求を識別します。「read_create」や「read_modify」などの新しいアクセス権限も使用できます。この拡張機能は、Data ONTAP API（ONTAPIまたはZAPI）と同じ機能を提供し、REST APIへのユーザの移行をサポートします。
パフォーマンスカウンタ:: ONTAP の以前のリリースでは、システムの動作特性に関する統計情報が管理されていました。9.11.1リリースでは、この情報が拡張され、REST APIから使用できるようになりました。管理者または自動プロセスは、データにアクセスしてシステムのパフォーマンスを判断できます。カウンタマネージャサブシステムが管理する統計情報は、テーブルと行を使用してデータベース形式で表示されます。この拡張機能により、ONTAP REST APIはData ONTAP API（ONTAPIまたはZAPI）と同等に機能します。
アグリゲートの管理:: ONTAP ストレージアグリゲートの管理が強化されました。更新されたRESTエンドポイントを使用して、アグリゲートをオンラインとオフラインに切り替えたり、スペアを管理したりできます。
IPサブネット機能:: ONTAP のネットワーク機能が拡張され、IPサブネットのサポートが追加されました。REST APIを使用すると、ONTAP クラスタ内のIPサブネットの設定と管理にアクセスできます。
複数の管理者の検証:: 複数の管理者による検証機能は、ONTAP のコマンドや操作へのアクセスを保護するための柔軟な認証フレームワークを提供します。制限されたコマンドを識別するルールを定義できます。ユーザから特定のコマンドへのアクセスが要求された場合、必要に応じて、複数のONTAP 管理者に承認を与えることができます。
SnapMirrorの機能拡張:: SnapMirror機能は、スケジュール設定など、いくつかの領域で強化されています。ONTAP 9.11.1のDP関係にSnapVault 関係のパリティも追加され、REST APIで使用できるスロットル機能は、Data ONTAP API（ONTAPIまたはZAPI）と同じ値に達しています。
ネームサービスキャッシュのサポート:: ONTAP ネームサービスが強化され、キャッシュがサポートされるようになり、パフォーマンスと耐障害性が向上しています。REST APIを使用してネームサービスキャッシュの設定にアクセスできるようになりました。設定は、ホスト、UNIXユーザ、UNIXグループ、ネットグループなど、複数のレベルで適用できます。




== ONTAP 9.10.1

ONTAP 9.10.1 では、引き続き ONTAP REST API の機能が拡張されています。ONTAP の新機能と既存の機能拡張をサポートするために、 100 以上の新しいエンドポイントが追加されています。次に、 REST API の拡張機能の概要を示します。

アプリケーション整合グループ:: 整合グループは、 Snapshot などの特定の処理を実行するときにグループ化される一連のボリュームです。この機能は、単一ボリュームの操作時に、クラッシュ整合性とデータ整合性を暗黙的に拡張したものです。大規模なマルチボリュームワークロードアプリケーションに有効です。
SVM 移行:: SVM は、ソースクラスタからデスティネーションクラスタに移行できます。新しいエンドポイントは、一時停止、再開、ステータスの読み出し、移行処理の中止など、すべての機能を制御します。
ファイルのクローニングと管理:: ボリュームレベルのファイルクローニングと管理が強化されました。新しい REST エンドポイントでは、ファイルの移動、コピー、およびスプリットの処理がサポートされます。
S3 監査の強化:: S3 イベントの監査は、セキュリティの向上によって特定の S3 イベントを追跡してログに記録できるようになりました。S3 監査イベントセレクタは、バケット単位で SVM 単位で設定できます。
ランサムウェア防御:: ONTAP は、ランサムウェアの脅威を含む可能性のあるファイルを検出しますこれらの疑わしいファイルのリストを取得したり、ボリュームから削除したりできます。
その他のセキュリティ機能強化:: 既存のプロトコルを拡張し、新しい機能を導入するための一般的なセキュリティ機能がいくつか強化されています。IPSec 、キー管理、 SSH 設定、およびファイル権限が改善されました。
CIFS ドメインおよびローカルグループ:: クラスタレベルおよび SVM レベルで CIFS ドメインのサポートが追加されました。ドメイン設定を取得したり、優先ドメインコントローラを作成および削除したりできます。
ボリューム分析を強化:: 上位のファイル、ディレクトリ、ユーザをサポートするために、追加のエンドポイントを通じてボリューム分析と指標が拡張されました。
サポートの強化:: サポートは、いくつかの新機能によって強化されています。自動更新では、最新のソフトウェア更新をダウンロードして適用することで、 ONTAP システムを最新の状態に保つことができます。ノードによって生成されたメモリコアダンプを取得および管理することもできます。




== ONTAP 9.9.1

ONTAP 9.9.1 では、引き続き ONTAP REST API の機能が拡張されています。SAN ポートセットや vServer ファイルディレクトリのセキュリティなど、既存の ONTAP 機能用の新しい API エンドポイントが追加されました。また、 ONTAP 9.9.1 の新しい機能と機能拡張をサポートするためにエンドポイントが追加されました。関連ドキュメントも改善されています。拡張機能の概要を以下に示します。

ONTAPI を ONTAP 9 REST API にマッピングしています:: ONTAP 自動化コードを REST API に移行するために、ネットアップでは API マッピングのドキュメントを提供しています。このリファレンスには、 ONTAPI コールのリストと、それぞれの REST API に相当する機能が含まれます。マッピングドキュメントが更新され、 ONTAP 9.9.1 の新しい API エンドポイントが追加されました。を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895["ONTAPI から REST API へのマッピング"^] を参照してください。
ONTAP 9.9.1 の新しいコア機能用の API エンドポイント:: ONTAPI API では使用できない ONTAP 9.9.1 の新しい機能のサポートが REST API に追加されました。ネストされた igroup と Google Cloud Key Management Services もサポートされます。
ONTAPI から REST への移行のサポートが改善されました:: 以前の ONTAPI コールのうち、対応する REST API に相当するものが追加されました。これには、ローカル UNIX ユーザとグループ、クライアント、 SAN ポートセット、ボリュームスペース属性を必要とせずに NTFS ファイルセキュリティを管理する作業が含まれます。これらの変更は、更新された ONTAPI から REST へのマッピングのドキュメントにも含まれます。
オンラインドキュメントが強化されました:: ONTAP オンラインドキュメントのリファレンスページに、 ONTAP 9.9..1 で新たに追加されたものも含め、各 REST エンドポイントまたはパラメータが導入されたときの ONTAP リリースを示すラベルが追加されました。




== ONTAP 9.8

ONTAP 9.8 では、 ONTAP REST API の幅と深さが大幅に拡張されています。ONTAP ストレージシステムの導入と管理を自動化する機能を強化する新機能がいくつか追加されています。さらに、以前の ONTAPI API からの REST への移行のサポートが強化されています。

ONTAPI を ONTAP 9 REST API にマッピングしています:: ONTAPI の自動化を更新するのに役立つように、 1 つ以上の入力パラメータを必要とする ONTAPI コールのリストと、それに相当する ONTAP 9 の REST API コールへのマッピングが提供されます。を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2874886["ONTAPI から REST API へのマッピング"^] を参照してください。
ONTAP 9.8 の新しいコア機能のための API エンドポイント:: ONTAPI では使用できない ONTAP 9.8 の新しいコア機能のサポートが REST API に追加されました。これには、 ONTAP S3 のバケットとサービス、 SnapMirror によるビジネス継続性、ファイルシステム分析での REST API のサポートが含まれます。
セキュリティ強化のための拡張サポート:: セキュリティは、 Azure Key Vault 、 Google Cloud Key Management Services 、 IPSec 、証明書署名要求などの複数のサービスとプロトコルをサポートすることで強化されています。
簡易性を向上するための機能拡張:: ONTAP 9.8 では、 REST API を使用して、より効率的で最新のワークフローを実現できます。たとえば、いくつかの種類のファームウェアで onecclick ファームウェアアップデートが利用できるようになりました。
オンラインドキュメントが強化されました:: ONTAP のオンラインドキュメントページに、 ONTAP のリリースを示すラベルが追加されました。これには、 9.8 で新たに追加されたものも含まれています。
ONTAPI から REST への移行のサポートが改善されました:: 以前の ONTAPI コールに対応する REST API に相当する機能が追加されました。既存の ONTAPI コールの代わりに使用する REST エンドポイントを特定する方法については、ドキュメントでも説明しています。
パフォーマンス指標の強化:: REST API のパフォーマンス指標が拡張され、いくつかの新しいストレージオブジェクトとネットワークオブジェクトが追加されました。




== ONTAP 9.7

ONTAP 9.7 では、 ONTAP REST API の機能を拡張するために、以下の 3 つの新しいリソースカテゴリが追加されています。それぞれに複数の REST エンドポイントが含まれています。

* NDMP
* オブジェクトストア
* SnapLock


ONTAP 9.7 では、既存のいくつかのリソースカテゴリに 1 つ以上の新しい REST エンドポイントが導入されています。

* クラスタ
* NAS
* ネットワーキング
* NVMe
* SAN
* セキュリティ
* ストレージ
* サポート




== ONTAP 9.6

ONTAP 9.6 は、 ONTAP 9.4 で導入された REST API のサポートを大幅に拡張します。ONTAP 9.6 REST API は、ほとんどの ONTAP 設定タスクおよび管理タスクをサポートします。

ONTAP 9.6 の REST API には、次のような重要な領域などがあります。

* クラスタセットアップ
* プロトコルの設定
* プロビジョニング
* パフォーマンスの監視
* データ保護
* アプリケーション対応のデータ管理

