---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= ONTAP REST API と自動化の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ネットアップでは、 ONTAP REST API を定期的に更新して、新機能、拡張機能、およびバグ修正を提供しています。



== ONTAP 9.10.1

ONTAP 9.10.1 では、引き続き ONTAP REST API の機能が拡張されています。ONTAP の新機能と既存の機能拡張をサポートするために、 100 以上の新しいエンドポイントが追加されています。次に、 REST API の拡張機能の概要を示します。

アプリケーション整合グループ:: 整合グループは、 Snapshot などの特定の処理を実行するときにグループ化される一連のボリュームです。この機能は、単一ボリュームの操作時に、クラッシュ整合性とデータ整合性を暗黙的に拡張したものです。大規模なマルチボリュームワークロードアプリケーションに有効です。
SVM 移行:: SVM は、ソースクラスタからデスティネーションクラスタに移行できます。新しいエンドポイントは、一時停止、再開、ステータスの読み出し、移行処理の中止など、すべての機能を制御します。
ファイルのクローニングと管理:: ボリュームレベルのファイルクローニングと管理が強化されました。新しい REST エンドポイントでは、ファイルの移動、コピー、およびスプリットの処理がサポートされます。
S3 監査の強化:: S3 イベントの監査は、セキュリティの向上によって特定の S3 イベントを追跡してログに記録できるようになりました。S3 監査イベントセレクタは、バケット単位で SVM 単位で設定できます。
ランサムウェア防御:: ONTAP は、ランサムウェアの脅威を含む可能性のあるファイルを検出しますこれらの疑わしいファイルのリストを取得したり、ボリュームから削除したりできます。
その他のセキュリティ機能強化:: 既存のプロトコルを拡張し、新しい機能を導入するための一般的なセキュリティ機能がいくつか強化されています。IPSec 、キー管理、 SSH 設定、およびファイル権限が改善されました。
CIFS ドメインおよびローカルグループ:: クラスタレベルおよび SVM レベルで CIFS ドメインのサポートが追加されました。ドメイン設定を取得したり、優先ドメインコントローラを作成および削除したりできます。

