---
sidebar: sidebar 
permalink: resources/cluster.html 
keywords: cluster resources 
summary: ONTAP クラスタと関連リソースの管理に使用できる API 呼び出しを次に示します。 
---
= ONTAP REST APIのクラスタリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP クラスタと関連リソースの管理に使用できる API 呼び出しを次に示します。

.容量プール
容量プールのライセンスモデルでは、各クラスタノードのストレージ容量のライセンスを共有プールから取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.シャーシ
シャーシは、クラスタをサポートするハードウェアフレームワークです。このリソースタイプは ONTAP 9.6 で導入されました。

.クラスタ
ONTAP クラスタには、 1 つ以上のノードと、ストレージシステムを定義する関連設定が含まれます。このリソースタイプは ONTAP 9.6 で導入されました。

.カウンタテーブル
ONTAP に関するさまざまな統計情報は、カウンタマネージャサブシステムによってキャプチャされます。この情報にアクセスして、システムのパフォーマンスを評価できます。このリソースタイプはONTAP 9.11で導入されました。

.ファームウェア
ファームウェア更新要求の履歴を取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.ジョブ
非同期 REST API 要求は、ジョブによってアンカーが設定されたバックグラウンドタスクを使用して実行されます。このリソースタイプは ONTAP 9.6 で導入されました。

.ライセンスインスタンス
各ライセンスは個別のパッケージとして管理できます。このリソースタイプは ONTAP 9.6 で導入されました。

.ライセンスマネージャ
ONTAP クラスタに関連付けられている各ライセンスマネージャインスタンスに関する設定やその他の情報を管理できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.ライセンス
ライセンスに基づいて、特定の ONTAP 機能を実装できます。このリソースタイプは ONTAP 9.6 で導入されました。

.メディエーターping
BlueXPクラウドサービスにpingを実行できます。このリソースタイプはONTAP 9.17.1で新しく追加されました。

.メディエーター
MetroClusterに関連付けられているメディエーターについて、インスタンスの追加や削除などの管理作業を実行できます。このリソース タイプはONTAP 9.8 で新しく追加され、9.17.1 で更新されました。

.MetroCluster
MetroCluster 環境を作成および管理して、スイッチオーバー処理やスイッチバック処理を実行できます。このリソースタイプはONTAP 9.8で新たに追加され、9.11で更新されました。

.MetroCluster 診断
MetroCluster 環境で診断処理を実行して、結果を取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.MetroCluster DR グループ
MetroCluster DR グループに関連する処理を実行できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.MetroCluster インターコネクト
MetroCluster インターコネクトのステータスを取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.MetroCluster ノード
MetroCluster 環境内の個々のノードのステータスを取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.MetroCluster 処理
MetroCluster 構成に対して最近実行された処理のリストを取得できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.MetroCluster SVM
MetroCluster 構成内のすべてのSVMペアに関する情報を取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

.ノード
ONTAP クラスタは 1 つ以上のノードで構成されます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。

.NTP キー
信頼できる外部 NTP タイムサーバと ONTAP の間で共有秘密鍵を使用するようにネットワークタイムプロトコル（ NTP ）を設定できます。このリソースタイプは ONTAP 9.7 で導入されました。

.NTP サーバ
外部 NTP サーバやキーなど、 ONTAP ネットワークタイムプロトコルを設定するために使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.7 で導入されました。

.ピア
ピアオブジェクトはエンドポイントを表し、クラスタピア関係をサポートします。このリソースタイプは ONTAP 9.6 で導入されました。

.パフォーマンスカウンタ
ONTAP の以前のリリースでは、システムの動作特性に関する統計情報が管理されていました。9.11.1リリースでは、この情報が拡張され、REST APIから使用できるようになりました。この機能を使用すると、ONTAP REST API（ONTAPIまたはZAPI）と同等の機能がData ONTAP APIに近くなります。このリソースタイプはONTAP 9.11で導入されました。

.リソースタグ
タグを使用してREST APIリソースをグループ化できます。これは、特定のプロジェクトまたは組織グループ内の関連リソースを関連付ける場合に行います。タグを使用すると、リソースをより効果的に整理および追跡できます。このリソースタイプはONTAP 9.13で導入されました。

.スケジュール
スケジュールを使用してタスクの実行を自動化できます。このリソースタイプは ONTAP 9.6 で導入されました。

.センサー
これらのエンドポイントを使用して、すべてのプラットフォーム環境センサーに関する詳細を取得できます。このリソースタイプはONTAP 9.11で導入されました。

.ソフトウェア
ONTAP クラスタには、クラスタソフトウェアプロファイル、ソフトウェアパッケージ情報、およびソフトウェア履歴情報が含まれます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。

.ウェブ：
これらのエンドポイントを使用して、 Web サービス設定を更新し、現在の設定を取得することができます。このリソースタイプは ONTAP 9.10 で導入されました。
