---
sidebar: sidebar 
permalink: resources/name_services.html 
keywords: name services resources 
summary: ONTAP でサポートされるネームサービスの管理に使用できる API 呼び出しを次に示します。 
---
= ネームサービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP でサポートされるネームサービスの管理に使用できる API 呼び出しを次に示します。

.キャッシュ
ONTAP ネームサービスは、パフォーマンスと耐障害性を向上させるキャッシュをサポートしています。REST APIを使用してネームサービスキャッシュを設定できるようになりました。設定は、ホスト、UNIXユーザ、UNIXグループ、ネットグループなど、複数のレベルで適用できます。このリソースタイプはONTAP 9.11で導入されました。

.DDNS
Dynamic DNS （ DDNS ；動的 DNS ）情報を表示し、 DDNS サブシステムを管理することができます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.DNS
DNS では、ネットワークでの ONTAP クラスタの統合がサポートされます。このリソースタイプは ONTAP 9.6 で導入されました。

.ホストレコード
これらのエンドポイントでは、指定したホスト名の IP アドレスと IP アドレスのホスト名を表示できます。このリソースタイプは ONTAP 9.10 で導入されました。

.LDAP
LDAP サーバを使用してユーザ情報を管理できます。このリソースタイプは ONTAP 9.6 で導入されました。

.LDAPスキーマ
ONTAP で使用するLDAPスキーマを作成、変更、および一覧表示できます。4つのデフォルトスキーマが含まれています。このリソースタイプはONTAP 9.11で導入されました。

.ローカルホスト
これらのエンドポイントを使用して、ホスト名のローカルマッピングを表示および管理できます。このリソースタイプは ONTAP 9.10 で導入されました。

.ネームマッピング
ネームマッピングを使用すると、特定のネームドメインから別のネームドメインに ID をマッピングできます。たとえば、 CIFS から UNIX 、 Kerberos から UNIX 、 UNIX から CIFS に識別子をマッピングできます。このリソースタイプは ONTAP 9.6 で導入されました。

.ネットグループファイル
ネットグループファイルの詳細を取得し、SVMのファイルを削除できます。このリソースタイプはONTAP 9.11で導入されました。

.NIS
NIS サーバは、ユーザやクライアントワークステーションの認証に使用できます。このリソースタイプは ONTAP 9.6 で導入されました。

.UNIX ユーザおよびグループ
ローカル UNIX ユーザおよびグループは、これまでの ONTAP リリースに含まれていました。ただし、 REST API のサポートが追加され、ユーザとグループを表示および管理できるようになりました。これらの REST リソースタイプは ONTAP 9.9 で導入され、 ONTAP 9.10 で大幅に拡張されました。
