---
sidebar: sidebar 
permalink: resources/nas.html 
keywords: nas resources 
summary: クラスタおよび SVM の CIFS と NFS の設定の管理に使用できる API 呼び出しを次に示します。 
---
= NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタおよび SVM の CIFS と NFS の設定の管理に使用できる API 呼び出しを次に示します。

ONTAP クラスタ用に定義されたActive Directoryアカウントを管理できます。これには、新しいアカウントの作成、アカウントの表示、更新、削除などが含まれます。このサポートはONTAP 9.12で追加されました。

SVM について、特定の CIFS イベントと NFS イベントをログに記録できます。この情報はセキュリティの向上に役立ちます。このリソースタイプは ONTAP 9.6 で導入されました。

NAS の監査イベントを特定の SVM にリダイレクトできます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

確立されたCIFS接続のリストを取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

CIFS ドメインのサポートがクラスタレベルおよび SVM レベルで追加され、いくつかのカテゴリのエンドポイントが用意されています。ドメイン設定を取得したり、優先ドメインコントローラを作成および削除したりできます。このリソースタイプは、 ONTAP 9.10 で新たに導入されました。

CIFSグループポリシーの作成と管理をサポートするためにエンドポイントが追加されている。設定情報は、すべてまたは特定のSVMに適用されるグループポリシーオブジェクトによって提供および管理されます。このサポートはONTAP 9.12で追加されました。

CIFS サーバ上に SMB ユーザのホームディレクトリを作成すると、ユーザごとに個別の SMB 共有を作成する必要がなくなります。ホームディレクトリ検索パスは、 SVM のルートからの絶対パスのセットです。このリソースタイプは ONTAP 9.6 で導入されました。

CIFS サーバでは、共有、ファイル、およびディレクトリのアクセス権を決定する際の許可にローカルグループを使用できます。このリソースタイプは ONTAP 9.9 で導入され、 ONTAP 9.10 で大幅に拡張されました。

クラスタのNetBIOS接続に関する情報を表示できます。詳細には、IPアドレスと登録されたNetBIOS名が含まれます。この情報は、名前解決に関する問題のトラブルシューティングに役立ちます。このリソースタイプはONTAP 9.11.1で導入されました。

CIFS サーバのコアの構成。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。

いくつかのフィルタリングオプションに基づいて、CIFSセッションの開いているファイルのリストを取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

この API を使用して、 CIFS セッションに関する詳細情報を取得できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で拡張されました。

Microsoftリモートボリュームシャドウコピーサービスは、Microsoft VSSの既存機能を拡張したものです。SMB共有のシャドウコピーにも対応するようにVSS機能が拡張されています。この機能は、ONTAP REST APIから使用できるようになりました。このリソースタイプはONTAP 9.11.1で導入されました。

CIFS サーバで定義されている SMB 共有。このリソースタイプは ONTAP 9.6 で導入されました。

CIFS 共有のフォルダおよびファイルへのアクセスを制御する Access Control List （ ACL ；アクセス制御リスト）。このリソースタイプは ONTAP 9.6 で導入されました。

CIFS クライアントと UNIX クライアントの両方から同じデータストアにアクセスできます。UNIX クライアントでシンボリックリンクを作成した場合、これらのマッピングによって、 CIFS クライアント用に別のファイルまたはフォルダへの参照が提供されます。このリソースタイプは ONTAP 9.6 で導入されました。

新しいREST APIエンドポイントを使用して、CIFSローカルユーザ、グループ、およびグループメンバーシップ情報を一括でインポートしたり、要求のステータスを監視したりできます。このリソースタイプはONTAP 9.11.1で導入されました。

特定のファイルへのアクセスをトレースするために使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.8 で新たに追加されました。

これらの API 呼び出しは、特定のファイルまたはフォルダに対して Windows ユーザまたは UNIX ユーザに付与されている有効な権限を表示します。NTFS ファイルセキュリティと監査ポリシーも管理できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で大幅に拡張されました。

FPolicy は、 SVM でファイルアクセスイベントの監視と管理に使用されるファイルアクセス通知フレームワークです。このリソースタイプは ONTAP 9.6 で導入されました。

これらのエンドポイントを使用すると、外部 FPolicy サーバの接続ステータス情報を表示および更新できます。このリソースタイプは ONTAP 9.10 で導入されました。

FPolicy エンジンを使用すると、ファイルアクセス通知を受信する外部サーバを識別できます。このリソースタイプは ONTAP 9.6 で導入されました。

ファイルアクセスの監視方法と生成されるイベントを識別する構成。このリソースタイプは ONTAP 9.6 で導入されました。

FPolicy エンジンやイベントなど、 FPolicy フレームワークの要素を格納するコンテナ。このリソースタイプは ONTAP 9.6 で導入されました。

ロックは、多数のクライアントが同じファイルに同時にアクセスしているファイルへの同時アクセスに制限を設けるための同期メカニズムです。これらのエンドポイントを使用して、ロックを取得および削除できます。このリソースタイプは ONTAP 9.10 で導入されました。

接続されているクライアントのNFSマップ情報を新しいエンドポイントから取得します。ノード、SVM、およびIPアドレスの詳細を取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

接続されているクライアントとその接続の詳細のリストを表示できます。このリソースタイプは ONTAP 9.7 で導入されました。

NFS エクスポートに関するルールを含むポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

Kerberos のインターフェイスの設定。このリソースタイプは ONTAP 9.6 で導入されました。

Kerberos Realm の設定。このリソースタイプは ONTAP 9.6 で導入されました。

NFS サーバのコアの構成。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。

S3 イベントの監査は、セキュリティの向上によって特定の S3 イベントを追跡してログに記録できるようになりました。S3 監査イベントセレクタは、バケット単位で SVM 単位で設定できます。このリソースタイプは ONTAP 9.10 で導入されました。

ウイルスやその他の悪意のあるコードからデータを保護するセキュリティ機能。このリソースタイプは ONTAP 9.6 で導入されました。

ファイルオブジェクトをクライアントからのアクセス時にアクティブにスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

ファイルオブジェクトをオンデマンドで即座にスキャンするか設定されたスケジュールに従ってスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

ONTAP と外部ウィルススキャンサーバの間の接続を管理するために使用される一連の属性。このリソースタイプは ONTAP 9.6 で導入されました。

外部ウィルススキャンサーバのステータス。このリソースタイプは ONTAP 9.6 で導入されました。
