---
sidebar: sidebar 
permalink: resources/nas.html 
keywords: nas resources 
summary: クラスタおよび SVM の CIFS と NFS の設定の管理に使用できる API 呼び出しを次に示します。 
---
= ONTAP REST APIのNASリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタおよび SVM の CIFS と NFS の設定の管理に使用できる API 呼び出しを次に示します。

.Active Directory
ONTAP クラスタ用に定義されたActive Directoryアカウントを管理できます。これには、新しいアカウントの作成、アカウントの表示、更新、削除などが含まれます。このサポートはONTAP 9.12で追加されました。

.監査
SVM について、特定の CIFS イベントと NFS イベントをログに記録できます。この情報はセキュリティの向上に役立ちます。このリソースタイプは ONTAP 9.6 で導入されました。

.監査ログのリダイレクト
NAS の監査イベントを特定の SVM にリダイレクトできます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.CIFS接続
確立されたCIFS接続のリストを取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

.CIFS ドメイン
CIFS ドメインのサポートがクラスタレベルおよび SVM レベルで追加され、いくつかのカテゴリのエンドポイントが用意されています。ドメイン設定を取得したり、優先ドメインコントローラを作成および削除したりできます。このリソースタイプはONTAP 9.10で導入され、ONTAP 9.13で拡張されました。

.CIFSグループポリシー
CIFSグループポリシーの作成と管理をサポートするためにエンドポイントが追加されている。設定情報は、すべてまたは特定のSVMに適用されるグループポリシーオブジェクトによって提供および管理されます。このサポートはONTAP 9.12で追加されました。

.CIFS ホームディレクトリ検索パス
CIFS サーバ上に SMB ユーザのホームディレクトリを作成すると、ユーザごとに個別の SMB 共有を作成する必要がなくなります。ホームディレクトリ検索パスは、 SVM のルートからの絶対パスのセットです。このリソースタイプは ONTAP 9.6 で導入されました。

.CIFS ローカルグループ
CIFS サーバでは、共有、ファイル、およびディレクトリのアクセス権を決定する際の許可にローカルグループを使用できます。このリソースタイプは ONTAP 9.9 で導入され、 ONTAP 9.10 で大幅に拡張されました。

.CIFS NetBIOSの場合
クラスタのNetBIOS接続に関する情報を表示できます。詳細には、IPアドレスと登録されたNetBIOS名が含まれます。この情報は、名前解決に関する問題のトラブルシューティングに役立ちます。このリソースタイプはONTAP 9.11.1で導入されました。

.CIFS サービス
CIFS サーバのコアの構成。このリソースタイプはONTAP 9.6で導入され、ONTAP 9.7および9.15で更新されました。

.CIFSセッションのファイル
いくつかのフィルタリングオプションに基づいて、CIFSセッションの開いているファイルのリストを取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

.CIFS セッション数
この API を使用して、 CIFS セッションに関する詳細情報を取得できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で拡張されました。

.CIFSシャドウコピー
Microsoftリモートボリュームシャドウコピーサービスは、Microsoft VSSの既存機能を拡張したものです。SMB共有のシャドウコピーにも対応するようにVSS機能が拡張されています。この機能は、ONTAP REST APIから使用できるようになりました。このリソースタイプはONTAP 9.11.1で導入されました。

.CIFS 共有
CIFS サーバで定義されている SMB 共有。このリソースタイプは ONTAP 9.6 で導入されました。

.CIFS 共有 ACL
CIFS 共有のフォルダおよびファイルへのアクセスを制御する Access Control List （ ACL ；アクセス制御リスト）。このリソースタイプは ONTAP 9.6 で導入されました。

.CIFS UNIX シンボリックリンクマッピング
CIFS クライアントと UNIX クライアントの両方から同じデータストアにアクセスできます。UNIX クライアントでシンボリックリンクを作成した場合、これらのマッピングによって、 CIFS クライアント用に別のファイルまたはフォルダへの参照が提供されます。このリソースタイプは ONTAP 9.6 で導入されました。

.CIFSユーザおよびグループの一括インポート
新しいREST APIエンドポイントを使用して、CIFSローカルユーザ、グループ、およびグループメンバーシップ情報を一括でインポートしたり、要求のステータスを監視したりできます。このリソースタイプはONTAP 9.11.1で導入されました。

.ファイルアクセスのトレース
特定のファイルへのアクセスをトレースするために使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.ファイルセキュリティ権限
これらの API 呼び出しは、特定のファイルまたはフォルダに対して Windows ユーザまたは UNIX ユーザに付与されている有効な権限を表示します。NTFS ファイルセキュリティと監査ポリシーも管理できます。このリソースタイプは、 ONTAP 9.8 REST API で導入され、 ONTAP 9.9 で大幅に拡張されました。

.FPolicy の
FPolicy は、 SVM でファイルアクセスイベントの監視と管理に使用されるファイルアクセス通知フレームワークです。このリソースタイプは ONTAP 9.6 で導入されました。

.FPolicy 接続
これらのエンドポイントを使用すると、外部 FPolicy サーバの接続ステータス情報を表示および更新できます。このリソースタイプは ONTAP 9.10 で導入されました。

.FPolicy エンジン
FPolicy エンジンを使用すると、ファイルアクセス通知を受信する外部サーバを識別できます。このリソースタイプは ONTAP 9.6 で導入されました。

.FPolicy イベント
ファイルアクセスの監視方法と生成されるイベントを識別する構成。このリソースタイプは ONTAP 9.6 で導入されました。

.FPolicy永続的ストア
ONTAP FPolicyの設定およびイベント用の永続的ストアを設定および管理できます。SVMごとに1つの永続的ストアを設定でき、SVM内の複数のポリシーで共有されます。このリソースタイプはONTAP 9.14で導入されました。

.FPolicy ポリシー
FPolicy エンジンやイベントなど、 FPolicy フレームワークの要素を格納するコンテナ。このリソースタイプは ONTAP 9.6 で導入されました。

.ロック
ロックは、多数のクライアントが同じファイルに同時にアクセスしているファイルへの同時アクセスに制限を設けるための同期メカニズムです。これらのエンドポイントを使用して、ロックを取得および削除できます。このリソースタイプは ONTAP 9.10 で導入されました。

.NFS接続クライアントマップ
接続されているクライアントのNFSマップ情報を新しいエンドポイントから取得します。ノード、SVM、およびIPアドレスの詳細を取得できます。このリソースタイプはONTAP 9.11.1で導入されました。

.NFS 接続クライアント
接続されているクライアントとその接続の詳細のリストを表示できます。このリソースタイプは ONTAP 9.7 で導入されました。

.NFS エクスポートポリシー
NFS エクスポートに関するルールを含むポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

.NFS Kerberos インターフェイス
Kerberos のインターフェイスの設定。このリソースタイプは ONTAP 9.6 で導入されました。

.NFS Kerberos Realm に移動します
Kerberos Realm の設定。このリソースタイプは ONTAP 9.6 で導入されました。

.TLS経由のNFS
このリソースを使用すると、NFS over TLSを使用する場合にインターフェイス設定を取得および更新できます。このリソースタイプはONTAP 9.15で導入されました。

.NFS サービス
NFS サーバのコアの構成。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。

.オブジェクトストア
S3 イベントの監査は、セキュリティの向上によって特定の S3 イベントを追跡してログに記録できるようになりました。S3 監査イベントセレクタは、バケット単位で SVM 単位で設定できます。このリソースタイプは ONTAP 9.10 で導入されました。

.vscan
ウイルスやその他の悪意のあるコードからデータを保護するセキュリティ機能。このリソースタイプは ONTAP 9.6 で導入されました。

.Vscan オンアクセスポリシー
ファイルオブジェクトをクライアントからのアクセス時にアクティブにスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

.Vscan オンデマンドポリシー
ファイルオブジェクトをオンデマンドで即座にスキャンするか設定されたスケジュールに従ってスキャンする際の Vscan ポリシー。このリソースタイプは ONTAP 9.6 で導入されました。

.Vscan スキャナプール
ONTAP と外部ウィルススキャンサーバの間の接続を管理するために使用される一連の属性。このリソースタイプは ONTAP 9.6 で導入されました。

.Vscan サーバステータス
外部ウィルススキャンサーバのステータス。このリソースタイプは ONTAP 9.6 で導入されました。
