---
sidebar: sidebar 
permalink: resources/nvme.html 
keywords: nvme resources 
summary: NVMeをサポートするリソースの管理に使用できるAPI呼び出しを次に示します。 
---
= NVMe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Non-Volatile Memory Express （ NVMe ）をサポートするリソースの管理に使用できる API 呼び出しを次に示します。

.Fibre Channel ログイン
Fibre Channel ログインは、 ONTAP にログインした Fibre Channel イニシエータによって確立された接続を表します。このリソースタイプは ONTAP 9.6 で導入されました。

.ネームスペース
NVMe ネームスペースは、 NVMe over Fabrics プロトコルを使用して SVM に接続されたホストに提供されるアドレス指定可能な論理ブロックの集まりです。このリソースタイプはONTAP 9.6で導入され、ONTAP 9.8で更新されました。パフォーマンス指標データの取得がONTAP 9.14でサポートされるようになりました。

.NVMe インターフェイス
NVMe インターフェイスは、 NVMe over Fabrics （ NVMe-oF ）プロトコルをサポートするように設定されたネットワークインターフェイスです。このリソースタイプは ONTAP 9.6 で導入されました。

.NVMe サービス
NVMe サービスは、 SVM の NVMe コントローラターゲットのプロパティを定義します。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。パフォーマンス指標データの取得がONTAP 9.14でサポートされるようになりました。

.NVMe サブシステムコントローラ
NVMe サブシステムコントローラは、ホストとストレージ解決策の間の動的な接続を表します。このリソースタイプは ONTAP 9.6 で導入されました。

.NVMe サブシステムマップ
NVMe サブシステムマップは、 NVMe ネームスペースと NVMe サブシステムの関連付けです。このリソースタイプは ONTAP 9.6 で導入されました。

.NVMe サブシステム
NVMe サブシステムは、 NVMe に接続された一連のホストの設定状態とネームスペースアクセス制御を管理します。このリソースタイプは ONTAP 9.6 で導入されました。
