---
sidebar: sidebar 
permalink: resources/object_store.html 
keywords: object store resources 
summary: S3 ベースのオブジェクトストレージへのアクセスに使用できる API 呼び出しを次に示します。 
---
= オブジェクトストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
S3 ベースのオブジェクトストレージへのアクセスに使用できる API 呼び出しを次に示します。

.バケット
バケットはオブジェクトのコンテナであり、オブジェクトネームスペースを使用して構成されます。各 S3 オブジェクトサーバに複数のバケットを含めることができます。このリソースタイプは ONTAP 9.7 で導入され、 ONTAP 9.8 で更新されました。

.バケットのSnapshot
S3バケットのSnapshotを作成および管理できます。この機能は、ONTAP 9 .16.1で追加されました。

.サービス
サーバやバケットの設定など、 ONTAP S3 設定を作成および管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.サービスバケット
バケットはオブジェクトのコンテナであり、オブジェクトネームスペースを使用して構成されます。特定の S3 サーバのバケットを管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.S3バケットルール
S3バケットにルール定義を含めることができます。各ルールはリストオブジェクトであり、バケット内のオブジェクトに対して実行される一連のアクションを定義します。このリソースタイプはONTAP 9.13で導入されました。

.S3 グループ
S3 ユーザのグループを作成し、グループレベルでアクセス制御を管理できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.S3 ポリシー
S3 ポリシーを作成してリソースに関連付け、さまざまな権限を定義することができます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.ユーザ
S3 ユーザアカウントは S3 サーバで管理されます。ユーザアカウントはキーのペアに基づいており、ユーザが制御するバケットに関連付けられています。このリソースタイプは ONTAP 9.7 で導入されました。
