---
sidebar: sidebar 
permalink: resources/security.html 
keywords:  
summary:  
---
= セキュリティ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタと SVM のセキュリティ設定の管理に使用できる API 呼び出しを次に示します。

.アカウント
クラスタと SVM の一連のユーザアカウントがあります。このリソースタイプは ONTAP 9.6 で導入されました。

.アカウント名
対象が指定されたユーザアカウントの構成。このリソースタイプは ONTAP 9.6 で導入されました。

.Active Directory プロキシ
Active Directory サーバの SVM アカウント情報を管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.ランサムウェア対策
ONTAP は、ランサムウェアの脅威を含む可能性のあるファイルを検出しますエンドポイントにはいくつかのカテゴリがあります。これらの疑わしいファイルのリストを取得したり、ボリュームから削除したりできます。このリソースタイプは ONTAP 9.10.1 で導入されました。

.監査
監査ログファイルに記録する内容を決定する設定。このリソースタイプは ONTAP 9.6 で導入されました。

.監査の送信先
これらの設定は、監査ログ情報をリモートシステムまたは Splunk サーバに転送する方法を制御します。このリソースタイプは ONTAP 9.6 で導入されました。

.監査メッセージ
監査ログメッセージを取得できます。このリソースタイプは ONTAP 9.6 で導入されました。

.AWS KMS
Amazon Web Servicesには、キーなどのシークレット用のセキュアなストレージを提供するキー管理サービスが含まれています。このサービスにはREST APIからアクセスできます。これにより、ONTAP は暗号化キーをクラウドにセキュアに格納できます。また、NetApp Storage Encryptionで使用する認証キーを作成して一覧表示することもできます。このサポートは、ONTAP 9.12で新たに追加されました。

.Azure キーバックアップ
この API 呼び出しセットを使用すると、 Azure Key Vault を使用して ONTAP 暗号化キーを格納できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.証明書
API 呼び出しを使用して、 ONTAP で使用される証明書をインストール、表示、および削除できます。このリソースタイプは ONTAP 9.7 で導入されました。

.クラスタセキュリティ
クラスタ全体のセキュリティの詳細を取得し、特定のパラメータを更新できます。このリソースタイプは ONTAP 9.7 で導入され、 ONTAP 9.8 で更新されました。

.GCP KMS
この API 呼び出しセットを使用すると、 Google Cloud Platform Key Management Service を使用して ONTAP 暗号化キーを格納および管理できます。このリソースタイプは、 ONTAP 9.8 REST API で最初に導入されました。ただし、この機能は再設計されているため、 ONTAP 9.9 で新しいリソースタイプであると見なされます。

.IPSec
IPSec は、基盤となる IP ネットワーク上の 2 つのエンドポイント間のセキュリティを提供するプロトコルのスイートです。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.IPSec CA 証明書
IPSec CA 証明書を追加、削除、および取得できます。このリソースタイプは、 ONTAP 9.10 で新たに導入されました。

.IPSec ポリシー
この一連の API 呼び出しを使用して、 IPSec 展開に有効なポリシーを管理できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.IPsec セキュリティアソシエーション
この一連の API 呼び出しを使用して、 IPSec 展開で有効なセキュリティアソシエーションを管理できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.キー管理ツールの設定
これらのエンドポイントを使用すると、キー管理ツールの設定を取得および更新できます。このリソースタイプは、 ONTAP 9.10 で新たに導入されました。

.キー管理ツール
キー管理ツールを使用すると、 ONTAP 内のクライアントモジュールでキーを安全に保管できます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 用に更新されました。認証キーをサポートするためにONTAP 9.12を使用する更新がもう1つありました。リストア機能がONTAP 9.13で追加されました。

.キーストア
キーストアとは、キー管理ツールのタイプを表します。このリソースタイプは、 ONTAP 9.10 で新たに導入されました。

.LDAP 認証
これらの API 呼び出しは、クラスタの LDAP サーバの構成を取得および管理するために使用します。このリソースタイプは ONTAP 9.6 で導入されました。

.ログインメッセージ
ONTAP で使用されるログインメッセージを表示および管理するために使用します。このリソースタイプは ONTAP 9.6 で導入されました。

.複数の管理者の検証
複数の管理者による検証機能は、ONTAP のコマンドや操作へのアクセスを保護するための柔軟な認証フレームワークを提供します。次の領域でアクセスの定義、要求、および承認をサポートする新しいエンドポイントは17個あります。

* ルール
* リクエスト
* 承認グループ


複数の管理者がアクセスを承認するオプションを指定すると、ONTAP およびIT環境のセキュリティが向上します。これらのリソースタイプはONTAP 9.11で導入されました。

.NIS 認証
これらの設定は、クラスタの NIS サーバの構成を取得および管理するために使用します。このリソースタイプは ONTAP 9.6 で導入されました。

.パスワード認証
これには、ユーザアカウントのパスワードの変更に使用される API 呼び出しが含まれます。このリソースタイプは ONTAP 9.6 で導入されました。

.ロールインスタンスの権限
特定のロールの権限を管理します。このリソースタイプは ONTAP 9.6 で導入されました。

.公開鍵による認証
ユーザアカウントの公開鍵の設定に使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.7 で導入されました。

.ロール
ロールを使用してユーザアカウントに権限を割り当てることができます。このリソースタイプは ONTAP 9.6 で導入されました。

.ロールインスタンス
ロールの特定のインスタンス。このリソースタイプは ONTAP 9.6 で導入されました。

.SAML サービスプロバイダ
SAML サービスプロバイダの設定を表示および管理できます。このリソースタイプは ONTAP 9.6 で導入されました。

.SSH
これらの呼び出しは、 SSH の設定に使用します。このリソースタイプは ONTAP 9.7 で導入されました。

.SSH SVMs
これらのエンドポイントを使用すると、すべての SVM の SSH セキュリティ設定を取得できます。このリソースタイプは ONTAP 9.10 で導入されました。

.TOTPS
REST APIを使用して、サインインしてSSHを使用してONTAP にアクセスするアカウントの時間ベースのワンタイムパスワード（TOTP）プロファイルを設定できます。このリソースタイプはONTAP 9.13で導入されました。
