---
sidebar: sidebar 
permalink: resources/snaplock.html 
keywords: snaplock resources 
summary: SnapLock 機能の管理に使用できる API 呼び出しを次に示します。 
---
= ONTAP REST APIのSnapLockリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
これらのAPI呼び出しを使用して、ONTAP SnapLock機能を管理できます。

.ログ
SnapLock のログ構造は、ログレコードを含む特定のボリュームのディレクトリとファイルに基づいています。ログファイルは、最大ログサイズに基づいていっぱいになり、アーカイブされます。このリソースタイプは ONTAP 9.7 で導入されました。

.コンプライアンスクロック
コンプライアンスクロックは、 SnapLock オブジェクトの有効期限を決定します。クロックは REST API の外部で初期化する必要があり、変更することはできません。このリソースタイプは ONTAP 9.7 で導入されました。

.イベント保持
SnapLock のイベントベースの保持（ EBR ）機能を使用して、特定のイベントの発生後にファイルを保持する期間を定義できます。このリソースタイプは ONTAP 9.7 で導入されました。

.ファイルの保持と privileged delete
SnapLock で作成されたファイルの保持期間を管理できます。必要に応じて、 SnapLock エンタープライズボリュームにある期限切れ前の WORM ファイルを削除することもできます。このリソースタイプは ONTAP 9.7 で導入されました。


NOTE: 削除操作を実行する権限を持つ組み込みのロールは vsadmin-snaplock だけです。

.ファイルフィンガープリント
タイプや有効期限など、ファイルとボリュームについてのコア情報を表示および管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.リーガルホールド
これらの API 呼び出しは、訴訟プロセスに関連するファイルの管理に使用できます。このリソースタイプは ONTAP 9.7 で導入されました。
