---
sidebar: sidebar 
permalink: resources/storage.html 
keywords: storage resources 
summary: 物理ストレージと論理ストレージの管理に使用できる API 呼び出しを次に示します。 
---
= ストレージ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
物理ストレージと論理ストレージの管理に使用できる API 呼び出しを次に示します。

.集計指標
特定のアグリゲートの指標の履歴データを取得できます。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。

.アグリゲートのプレックス
アグリゲート内の WAFL ストレージの物理コピー。このリソースタイプは ONTAP 9.6 で導入されました。

.アグリゲート
アグリゲートは 1 つ以上の RAID グループで構成されます。このリソースタイプは ONTAP 9.6 で導入されました。

.ブリッジ
クラスタ内のブリッジを取得できます。このリソースタイプは ONTAP 9.9 で導入されました。

.ディスク
クラスタ内の物理ディスク。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 および 9.8 で更新されました。

.ファイルクローン
これらのエンドポイントを使用して、ファイルクローンの作成、スプリットステータスの取得、およびスプリット負荷の管理を行うことができます。ファイルクローニングのエンドポイントリソースは、 ONTAP 9.6 で初めて導入され、 ONTAP 9.8 で拡張されました。ONTAP 9.10 で再び大幅に拡張されました。

.ファイル移動
これらのREST APIエンドポイントを使用して、2つのFlexVol 間またはFlexGroup ボリューム内でファイルを移動できます。要求を承認したら、進捗状況とステータスを監視できます。このリソースタイプはONTAP 9.11.1で導入されました。

.FlexCache
このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.8 で更新されました。

.FlexCache の原点
FlexCache は、元のボリュームの永続的なキャッシュです。このリソースタイプは、もともと ONTAP 9.6 で導入されたものです。ONTAP 9.9 REST API によるサポートが強化され、 HTTP パッチメソッドによる変更がサポートされるようになりました。

.監視対象ファイル
特定のファイルを追加監視用に指定できます。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.プール
共有ストレージプールを作成したり、クラスタ内のストレージプールを取得したりできます。このリソースタイプはONTAP 9.11.1で導入されました。

.ポート
クラスタのストレージポート。このリソースタイプはONTAP 9.6で導入され、ONTAP 9.11.1で拡張されました。

.QoS ポリシー
QoS ポリシーの設定。このリソースタイプは ONTAP 9.6 で導入されました。

.QoS ワークロード
QoS ワークロードとは、 QoS によって追跡されるストレージオブジェクトのことです。QoS ワークフローを取得できます。このリソースタイプは ONTAP 9.10 で導入されました。

.qtree
論理的に分割されたファイルシステムの一種である管理 qtree への API 呼び出しを次に示します。このリソースタイプは ONTAP 9.6 で導入されました。

.クォータレポート
クォータに関するレポート。クォータは、ファイルまたはスペースの使用を制限または追跡するための手法です。このリソースタイプは ONTAP 9.6 で導入されました。

.クォータルール
クォータの適用に使用されるルール。このリソースタイプは ONTAP 9.6 で導入され、 ONTAP 9.7 で更新されました。

.シェルフ
クラスタ内のシェルフ。このリソースタイプは ONTAP 9.6 で導入されました。

.Snapshot ポリシー
Snapshot はポリシーに基づいて作成されます。このリソースタイプは ONTAP 9.6 で導入されました。

.Snapshot スケジュール
Snapshot スケジュールを制御できます。このリソースタイプは、 ONTAP 9.8 で新たに再設計されました。

.スイッチ
クラスタ内のスイッチを取得できます。このリソースタイプは ONTAP 9.9 で導入されました。

.テープデバイス
クラスタ内のテープデバイスを取得できます。このリソースタイプは ONTAP 9.9 で導入されました。

.上位の指標
上位の指標エンドポイントでは、特定の指標でフィルタされたボリュームのアクティビティを確認できます。クライアント、ディレクトリ、ファイル、およびユーザに基づいてフィルタリングを実行できます。このリソースタイプは ONTAP 9.10 で導入されました。

.ボリューム効率化ポリシー
ボリューム全体に効率化を設定するために使用できる API 呼び出しを次に示します。このリソースタイプは ONTAP 9.8 で新たに追加されました。

.個のボリューム
論理コンテナは、クライアントにデータを提供するために使用されます。このリソースタイプは、元々は ONTAP 9.6 REST API で導入されました。API で使用されるパラメータ値の多くは、 ONTAP 9.9 で大幅に拡張されました。これには、スペース管理で使用される値も含まれます。

.ボリュームファイル
ボリューム上の特定のディレクトリのファイルとディレクトリのリストを取得できます。このリソースタイプは ONTAP 9.7 で導入され、 ONTAP 9.8 で更新されました。

.ボリューム Snapshot
ボリュームの Snapshot 。このリソースタイプは ONTAP 9.6 で導入されました。
