---
sidebar: sidebar 
permalink: resources/support.html 
keywords: support resources 
summary: クラスタのサポートに使用される ONTAP 機能の管理に使用できる API 呼び出しを次に示します。 
---
= サポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタのサポートに使用される ONTAP 機能の管理に使用できる API 呼び出しを次に示します。

.アプリケーションログ
スタンドアロンアプリケーションでは、POST要求を発行することで、ONTAP システムにEMSイベントとオプションで生成されたAutoSupport パッケージを記録できます。このリソースタイプはONTAP 9.11.1で導入されました

.自動更新
自動更新機能は、最新のソフトウェア更新をダウンロードして適用することで、 ONTAP システムを最新の状態に保ちます。この機能は、ステータス、設定、更新など、いくつかのエンドポイントカテゴリでサポートされます。これらのリソースタイプは ONTAP 9.10 で導入されました。

.AutoSupport
AutoSupport は、構成やステータスの詳細およびエラーを収集してネットアップに情報を報告します。このリソースタイプは ONTAP 9.6 で導入されました。

.AutoSupport メッセージ
各ノードで生成および取得できる AutoSupport メッセージが管理されます。このリソースタイプは ONTAP 9.6 で導入されました。

.構成のバックアップ
これらの API を使用して、現在のバックアップ設定を取得および更新できます。このリソースタイプは ONTAP 9.6 で導入されました。

.構成のバックアップ処理
構成バックアップファイルを作成、取得、および削除できます。このリソースタイプは ONTAP 9.7 で導入されました。

.コアダンプ
これらのエンドポイントを使用して、クラスタまたはノードによって生成されたメモリコアダンプを取得および管理できます。このリソースタイプは ONTAP 9.10 で導入されました。

.EMS
Event Management System （ EMS ；イベント管理システム）は、イベントを収集して 1 つ以上のデスティネーションに通知を送信します。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS デスティネーション
EMS デスティネーションによって、通知の送信方法と送信先が決まります。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS デスティネーションインスタンス
EMS デスティネーションインスタンスは、タイプと場所で定義されます。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS イベント
クラスタの最新のシステムイベントを収集したものです。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS フィルタ
EMS フィルタは、追加の処理が必要なイベントをまとめて識別します。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS フィルタインスタンス
EMS フィルタインスタンスは、イベントに適用されるルールの集まりです。このリソースタイプは ONTAP 9.6 で導入されました。

.EMS メッセージです
EMS イベントカタログへのアクセスを提供します。このリソースタイプは ONTAP 9.6 で導入されました。

.フィルタインスタンスの EMS ルール
EMS フィルタの特定のインスタンスに対するルールのリストを管理できます。このリソースタイプは ONTAP 9.6 で導入されました。

.フィルタインスタンスの EMS ルールインスタンス
EMS フィルタの特定のインスタンスに対する個別のルール。このリソースタイプは ONTAP 9.6 で導入されました。

.SNMP
クラスタの SNMP およびトラップ操作を有効または無効にできます。このリソースタイプは ONTAP 9.7 で導入されました。

.SNMP トラップホスト
SNMP トラップホストは、 ONTAP から SNMP トラップを受信するように設定されたシステムです。ホストを取得および定義できます。このリソースタイプは ONTAP 9.7 で導入されました。

.SNMP トラップホストインスタンス
特定の SNMP トラップホストを管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.SNMP ユーザ
SNMP ユーザを定義および管理できます。このリソースタイプは ONTAP 9.7 で導入されました。

.SNMP ユーザインスタンス
エンジン ID が管理 SVM またはデータ SVM に関連付けられた特定の SNMP ユーザを管理できます。このリソースタイプは ONTAP 9.7 で導入されました。
