---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: ONTAP ストレージシステムの導入と管理を自動化する方法については、他にもいくつかのリソースをヘルプしたり、詳細情報を参照したりすることができます。 
---
= ONTAP REST APIの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPストレージシステムの導入と管理を自動化するための参考資料がいくつか用意されています。



== ブログ記事

ブログ記事は、主題に基づいていくつかのセクションに配置されています。



=== 全般

* 現在のONTAP自動化テクノロジの概要です。
+
https://www.netapp.com/blog/new-normal-for-automation["自動化の新たな標準"^]

* ONTAPイベントを監視して、システムアクティビティを常に把握できます。これらのイベントの設定と管理は、REST APIを使用して自動化できます。
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST API ：重大度の高いイベントの通知を自動化します"^]

* コーヒーブレークウィズREST（6エピソード）：
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["ONTAP REST APIの基礎"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["ONTAP RESTAPIノキノウ"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Postmanを使用したONTAP RESTのハンズオン"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["ONTAPI（ZAPI）レポートツール"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["プライベートCLIパススルー"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["ONTAPストレージの自動化をシンプルにする5つの魔法の機能！"^]






=== Python クライアントライブラリ

* このブログでは、ONTAP Pythonクライアントライブラリの機能を簡単に紹介します。
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["PythonクライアントライブラリでONTAP REST APIの利用を簡易化"^]





=== REST APIへの移行

* REST APIをベースにしたONTAP 自動化環境の変革に役立つテクノロジがいくつかあります。
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["ONTAPIから自動化をONTAP REST APIに変換します"^]





== ビデオ

* NetApp Pythonクライアントライブラリの入門と、ライブラリを使用してコードを書き始める方法を紹介します。
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Ansible認定モジュールをご覧ください。
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* NetApp TechComm TVのビデオコレクション。
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["NetApp ONTAP管理の自動化"^]





== ネットアップナレッジベース

* ONTAP REST APIで問題が発生した場合は、NetAppに報告できます。
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["ONTAP REST APIおよびONTAP REST API Pythonクライアントライブラリに関する問題の報告方法"^]

* ONTAP REST APIの機能ギャップが見つかった場合は、APIの新しい機能を要求できます。
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["ONTAP REST APIの機能を要求する方法"^]


