---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: ONTAP ストレージシステムの導入と管理を自動化する方法については、他にもいくつかのリソースをヘルプしたり、詳細情報を参照したりすることができます。 
---
= その他のリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP ストレージシステムの導入と管理を自動化する方法については、他にもいくつかのリソースをヘルプしたり、詳細情報を参照したりすることができます。



== ONTAP 9 のリソース

* https://docs.netapp.com/us-en/ontap-family/["ONTAP 9製品ドキュメント"^]
+
ONTAP 9製品ファミリーのドキュメントを提供します。

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP リリースノート"^]
+
現在のリリースに関する情報が記載されたONTAP 9リリースノート。

* https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["ONTAP および ONTAP System Manager の関連リソース"^]
+
ONTAP 9の計画、管理、およびサポートに必要なマニュアルとその他の役立つリンクが含まれています。

* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 製品ライブラリ"^]
+
以前のONTAP リリースのリリースノートやその他のドキュメントにアクセスする





== ONTAP 9 開発者向けリソース

* link:../migrate/mapping.html["ONTAPI から REST API へのマッピング"]
+
主なONTAPIコールと、それに相当するREST APIコールとのマッピングを提供します。適切なONTAP リリースを選択します。

* https://pypi.org/project/netapp-ontap["PyPi：NetApp ONTAP の略"^]
+
PyPi の NetApp Python Client Library パッケージです。

* https://library.netapp.com/ecmdocs/ECMLP2885777/html/index.html["9.13.1用のNetApp PCLドキュメント"^]
+
NetApp Python クライアントライブラリのドキュメント

* https://devnet.netapp.com/restapi.php["ネットアップ開発者ネットワーク： ONTAP RESTful API"^]
+
ONTAP Python クライアントライブラリなど、 ONTAP REST API の使用に必要なリソースとドキュメントを提供します。





== ビデオ

* https://www.youtube.com/watch?v=Wws3SB5d9Ss["NetApp ONTAP Python クライアントライブラリの使用を開始する"^]
+
NetApp Python クライアントライブラリの概要と、ライブラリを使用してコードを記述する方法について説明します。





== ネットアップのリソース

* https://mysupport.netapp.com/["ネットアップサポート"^]
+
トラブルシューティングツール、ドキュメント、およびテクニカルサポートにアクセスできます。

* https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]
+
ONTAP 9 および ONTAP REST API の使用に関連する要件と互換性の情報を確認できます。

* http://www.netapp.com/us/library/index.aspx["テクニカルレポートとホワイトペーパーのネットアップライブラリです"^]
+
テクニカルレポート、ホワイトペーパー、その他のドキュメントにアクセスできます。


