---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: ONTAP ストレージシステムの導入と管理を自動化する方法については、他にもいくつかのリソースをヘルプしたり、詳細情報を参照したりすることができます。 
---
= その他のリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPストレージシステムの導入と管理を自動化するための参考資料がいくつか用意されています。



== ONTAP 9 のリソース

* ONTAP 9製品ファミリーのドキュメントを提供します。
+
https://docs.netapp.com/us-en/ontap-family/["ONTAP 9製品ドキュメント"^]

* 現在のリリースに関する情報が記載されたONTAP 9リリースノート。
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP リリースノート"^]

* ONTAP 9の計画、管理、およびサポートに必要なマニュアルとその他の役立つリンクが含まれています。
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["ONTAP および ONTAP System Manager の関連リソース"^]

* 以前のONTAP リリースのリリースノートやその他のドキュメントにアクセスする
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["ONTAP 9 製品ライブラリ"^]





== ONTAP 9 開発者向けリソース

* DevOps環境でAnsibleの使用を開始するのに役立ちます。
+
https://www.netapp.com/devops-solutions/ansible/["ネットアップの Ansible DevOps ソリューション"^]

* 主なONTAPIコールと、それに相当するREST APIコールとのマッピングを提供します。適切なONTAP リリースを選択します。
+
link:../migrate/mapping.html["ONTAPI から REST API へのマッピング"]

* PyPi の NetApp Python Client Library パッケージです。
+
https://pypi.org/project/netapp-ontap["PyPi：NetApp ONTAP の略"^]

* NetApp Python クライアントライブラリのドキュメント
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html["9.14.1用NetApp PCLドキュメント"^]

* ONTAP REST APIの使用に必要なリソースとドキュメントを提供します。
+
https://devnet.netapp.com/restapi.php["ネットアップ開発者ネットワーク： ONTAP RESTful API"^]





== ブログ記事

* CLI パススルーは、 REST API を使用して ONTAP CLI コマンドを実行するための技術です。
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["ONTAP REST API でプライベート CLI パススルーを使用する"^]

* Ansible for ONTAP 自動化を初めて使用する方には、この作業を始めることをお勧めします。
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["ネットアップと Ansible の使用： Ansible のインストール"^]





== ビデオ

* NetApp Pythonクライアントライブラリの入門と、ライブラリを使用してコードを書き始める方法を紹介します。
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss["NetApp ONTAP Python クライアントライブラリの使用を開始する"^]

* このビデオは、NetApp TVからも入手できます。 link:https://tv.netapp.com/detail/video/6217195551001["Ansible 認定モジュール"^]。
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Ansible認定モジュールをご覧ください。
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]




== ネットアップのリソース

* トラブルシューティングツール、ドキュメント、およびテクニカルサポートにアクセスできます。
+
https://mysupport.netapp.com/["ネットアップサポート"^]

* ONTAP 9 および ONTAP REST API の使用に関連する要件と互換性の情報を確認できます。
+
https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]

* テクニカルレポート、ホワイトペーパー、その他のドキュメントにアクセスできます。
+
http://www.netapp.com/us/library/index.aspx["テクニカルレポートとホワイトペーパーのネットアップライブラリです"^]


