---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation 
summary: APIリファレンスには、HTTPメソッド、入力パラメータ、応答など、すべてのONTAP REST API呼び出しに関する詳細が含まれています。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。 
---
= API リファレンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
APIリファレンスには、HTTPメソッド、入力パラメータ、応答など、すべてのONTAP REST API呼び出しに関する詳細が含まれています。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。


NOTE: オンラインのAPIリファレンスコンテンツには、ローカルのONTAP システムからアクセスできます。または、ネットアップが管理するドキュメントの静的なコピーにもアクセスできます。



== ONTAP API ドキュメントページにアクセスします

[role="lead"]
ONTAP API オンラインドキュメントページは、ローカルの ONTAP システムからアクセスできます。

次の情報が必要です。

* ONTAP クラスタ管理 LIF の IP アドレスまたはホスト名
* ONTAP REST API にアクセスする権限を持つアカウントのユーザ名とパスワード


.手順
. ブラウザに URL を入力し、 *Enter* キーを押します。
+
https://<ip_address>/docs/api`

. ONTAP アカウントを使用してサインインします。
+
ONTAP API ドキュメントページが表示され、主要なリソースカテゴリ別に分類された API 呼び出しが下部に表示されます。

. 個々の API 呼び出しの例として、 * cluster * カテゴリまでスクロールし、 * get/cluster * をクリックします。




== ONTAP REST APIリファレンスドキュメントのコピーにアクセスする

[role="lead"]
ONTAP REST APIリファレンスドキュメントのコピーには、以下のリンクからアクセスできます。APIリファレンスドキュメントは、ONTAP リリースで管理されています。

* https://library.netapp.com/ecmdocs/ECMLP2884821/html/["ONTAP 9.12.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2882307/html/["ONTAP 9.11.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2879871/html/["ONTAP 9.10.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2876964/html/["ONTAP 9.9.1"^]
* https://library.netapp.com/ecmdocs/ECMLP2874708/html/["ONTAP 9.8"^]
* https://library.netapp.com/ecmdocs/ECMLP2862544/html/["ONTAP 9.7"^]
* https://library.netapp.com/ecmdocs/ECMLP2856304/html/["ONTAP 9.6"^]


https://devnet.netapp.com/restapi.php["ネットアップの DevNet ： ONTAP REST API"^]
