---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation, online reference, swagger 
summary: APIリファレンスには、ONTAP REST API呼び出しの詳細（HTTPメソッド、入力パラメータ、応答など）が記載されています。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。 
---
= API リファレンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
APIリファレンスには、ONTAP REST API呼び出しの詳細（HTTPメソッド、入力パラメータ、応答など）が記載されています。このリファレンスは、 REST API を使用して自動化アプリケーションを開発する場合に役立ちます。


NOTE: ONTAPリリースに基づいて、いくつかのサイトのいずれかでREST APIのリファレンスドキュメントにアクセスできます。同等のドキュメントのコピーは、ローカルのONTAPシステムのSwagger UIからも入手できます。



== ONTAP APIのリファレンスドキュメントへのオンラインアクセス

最新のドキュメントにはオンラインでアクセスでき https://docs.netapp.com/us-en/ontap-restapi/ontap/getting_started_with_the_ontap_rest_api.html["ONTAP REST APIリファレンス"^]ます。ONTAPリリースに基づく以前のバージョンのドキュメントにアクセスするためのバージョンセレクタも用意されています。



== Swagger UIからONTAP APIのリファレンスドキュメントにアクセス

ONTAP REST APIのドキュメントには、ローカルのONTAPシステムのSwagger UIからアクセスできます。

.作業を開始する前に
次の情報が必要です。

* ONTAP クラスタ管理 LIF の IP アドレスまたはホスト名
* ONTAP REST API にアクセスする権限を持つアカウントのユーザ名とパスワード


.手順
. ブラウザに URL を入力し、 *Enter* キーを押します。
+
https://<ip_address>/docs/api`

. ONTAP アカウントを使用してサインインします。
+
ONTAP API ドキュメントページが表示され、主要なリソースカテゴリ別に分類された API 呼び出しが下部に表示されます。

. 個々の API 呼び出しの例として、 * cluster * カテゴリまでスクロールし、 * get/cluster * をクリックします。

