---
sidebar: sidebar 
permalink: workflows/prepare_workflows.html 
keywords:  
summary:  
---
= ワークフローを使用する準備をします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ワークフロープロセスを使用する前に準備しておく必要があります。



=== ワークフローで使用する API 呼び出しについて

ONTAP API オンラインドキュメントページに、すべての REST API 呼び出しの詳細が記載されています。ここでは、それらの詳細を繰り返すのではなく、ワークフローのサンプルで使用している各 API 呼び出しについて、その呼び出しをドキュメントページで見つけるために必要な情報だけを示しています。特定の API 呼び出しを検索すると、入力パラメータ、出力形式、 HTTP ステータスコード、要求処理タイプなど、呼び出しのすべての詳細を確認できます。

ワークフロー内の各 API 呼び出しについて、ドキュメントページで検索するのに役立つ次の情報が含まれています。

* カテゴリ
+
ドキュメントページでは、機能的な関連領域またはカテゴリ別に API 呼び出しが分類されています。特定の API 呼び出しを検索するには、ページの一番下までスクロールして、該当する API カテゴリをクリックします。

* HTTP メソッド
+
HTTP メソッドは、リソースに対して実行されるアクションを識別します。各 API 呼び出しは、単一の HTTP メソッドを使用して実行されます。

* パス
+
このパスは、呼び出しの実行中に環境アクションが実行する特定のリソースを指定します。パス文字列がコア URL に追加され、リソースを識別する完全な URL が形成されます。





=== REST API に直接アクセスするための URL の作成

ONTAP のドキュメントページに加え、 Python などのプログラミング言語を使用して、 ONTAP REST API に直接アクセスすることもできます。この場合のコア URL は、オンラインドキュメントページにアクセスするときに使用する URL とは少し異なります。API に直接アクセスする場合は ' ドメインとポート文字列に /api' を付加する必要がありますたとえば、「 https://ontap.mycompany.com/api` 」と入力します

.関連リンク
* link:../rest/access_rest_api.html["ONTAP API へのアクセス方法"]
* link:../resources/overview_categories.html["REST リソースの概要"]

