---
sidebar: sidebar 
permalink: workflows/wf_ems_create_notification.html 
keywords: support, ems, event management system, create ems, create ems notification 
summary: 次のワークフローを使用して、選択したイベントメッセージを受信する新しいEMS通知の送信先を作成できます。 
---
= EMS通知を作成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次のワークフローを使用して、選択したイベントメッセージを受信する新しいEMS通知の送信先を作成できます。



== 手順1：システム全体のEメール設定を構成する

次のAPI呼び出しを問題して、システム全体のEメール設定を行うことができます。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| パッチ | /api/support/ems 
|===
.処理のタイプ
同期

.Curlの例の追加入力パラメータ
すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| メールの差出人 | クエリ | はい。 | を設定します。 `from` フィールドをクリックします。 


| メールサーバ | クエリ | はい。 | ターゲットのSMTPメールサーバを設定します。 
|===
.カールの例
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----


== 手順2：メッセージフィルタを定義する

API呼び出しを問題して、メッセージに一致するフィルタルールを定義できます。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /api/support/ems/filters 
|===
.処理のタイプ
同期

.Curlの例の追加入力パラメータ
すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| フィルタ | ボディ（ Body ） | はい。 | フィルタ設定の値が含まれます。 
|===
.カールの例
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/filters" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON の入力例
[source, json]
----
{
  "name": "test-filter",
  "rules.type": ["include"],
  "rules.message_criteria.severities": ["emergency"]
}
----


== 手順3：メッセージの送信先を作成する

API呼び出しを問題して、メッセージの送信先を作成できます。

.HTTPメソッドとエンドポイント
このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

[cols="25,75"]
|===
| HTTP メソッド | パス 


| 投稿（ Post ） | /api/support/ems/destinations 
|===
.処理のタイプ
同期

.Curlの例の追加入力パラメータ
すべての REST API 呼び出しに共通するパラメータに加えて、この手順の curl の例では次のパラメータも使用されます。

[cols="25,10,10,55"]
|===
| パラメータ | を入力します | 必須 | 説明 


| デスティネーションの設定 | ボディ（ Body ） | はい。 | イベントの送信先の値が含まれます。 
|===
.カールの例
[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP/api/support/ems/destinations" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.JSON の入力例
[source, curl]
----
{
  "name": "test-destination",
  "type": "email",
  "destination": "administrator@mycompany.com",
  "filters.name": ["important-events"]
}
----