---
sidebar: sidebar 
permalink: workflows/wf_rbac_prepare.html 
keywords: security, rbac, prepare rbac, rbac workflows 
summary: ONTAP RBAC機能は、環境に応じていくつかの方法で使用できます。このセクションでは、いくつかの一般的なシナリオをワークフローとして紹介します。いずれの場合も、特定のセキュリティおよび管理上の目標に焦点を当てています。 
---
= RBACを使用するための準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP RBAC機能は、環境に応じていくつかの方法で使用できます。このセクションでは、いくつかの一般的なシナリオをワークフローとして紹介します。いずれの場合も、特定のセキュリティおよび管理上の目標に焦点を当てています。

ロールを作成してONTAPユーザアカウントにロールを割り当てる前に、次に示す主なセキュリティ要件とオプションを確認して準備しておく必要があります。また、次のWebサイトで一般的なワークフローの概念を確認してください。 link:../workflows/prepare_workflows.html["ワークフローを使用する準備をします"]。

.どのONTAP リリースを使用していますか？
ONTAP リリースによって、使用可能なRESTエンドポイントとRBAC機能が決まります。

.保護対象のリソースと範囲を特定
保護対象のリソースまたはコマンドとその範囲（クラスタまたはSVM）を特定する必要があります。

.ユーザにはどのようなアクセス権が必要ですか。
リソースと範囲を特定したら、許可するアクセスレベルを決定する必要があります。

.ユーザはどのようにONTAP にアクセスしますか。
ユーザはREST API、CLI、またはその両方を使用してONTAP にアクセスできます。

.組み込みの役割の1つで十分か、またはカスタムの役割が必要か。
既存の組み込みロールを使用する方が便利ですが、必要に応じて新しいカスタムロールを作成することもできます。

.どのような種類の役割が必要ですか？
セキュリティ要件とONTAP アクセスに基づいて、RESTと従来のどちらのロールを作成するかを選択する必要があります。
