---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: ONTAP REST API には、いくつかの方法でアクセスできます。 
---
= ONTAP REST APIにアクセスする方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP REST API には、いくつかの方法でアクセスできます。



== ネットワークに関する考慮事項

いくつかのタイプのインターフェイスのいずれかを使用して、 ONTAP REST API に接続できます。選択する LIF は、HTTPS 管理プロトコルをサポートするように設定する必要があります。また、ネットワークのファイアウォール構成で HTTPS トラフィックを許可する必要があります。次のインターフェースがサポートされています。

* クラスタ管理 LIF
* ノード管理 LIF
* SVM 管理 LIF


これらの LIF はどれでも使用できますが、推奨されるベスト プラクティスはクラスタ管理 LIF を使用することです。これにより、クラスターを単一の論理ユニットとしてアドレス指定できるようになり、最高レベルの回復力と負荷分散が実現します。クラスタ LIF は、計画されたアップグレード、クォーラム イベント、およびその他の接続の問題を処理するために、必要に応じてクラスタ内で再配置できます。複数のクラスタ管理 LIF が設定されている場合、REST API へのアクセスに関してはそれらはすべて同等になります。SVM 管理 LIF も負荷分散されますが、ノード レベルでスコープされた LIF に送信された要求はローカルで処理されます。



== ONTAP API オンラインドキュメントページ

ONTAP API オンラインドキュメントページに、 Web ブラウザを使用する際のアクセスポイントが記載されています。個々の API 呼び出しを直接実行する方法に加え、各呼び出しの入力パラメータやその他のオプションなど、 API の詳細な概要も含まれています。API 呼び出しは機能のカテゴリ別に分類されています。を参照してください link:../resources/overview_categories.html["REST リソースの概要"] を参照してください。

最新バージョンの API のドキュメントページにアクセスするための URL の形式は次のとおりです。

`\https://<cluster_mgmt_ip_address>/docs/api`



== カスタムのソフトウェアとツール

ONTAP API には、さまざまなプログラミング言語やツールを使用してアクセスできます。代表的なものとしては、 Python 、 Java 、 Curl 、 PowerShell などがあります。API を使用するプログラム、スクリプト、またはツールは、 REST Web サービスのクライアントとして機能します。プログラミング言語を使用すると、 API についての理解が深まり、 ONTAP の管理を自動化することもできます。

最新バージョンの API に直接アクセスするためのベース URL の形式は次のとおりです。

`\https://<cluster_mgmt_ip_address>/api`

複数のバージョンがサポートされている場合に特定のバージョンの API にアクセスするには、次の形式の URL を使用します。

`\https://<cluster_mgmt_ip_address>/api/v1`
