---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog 
summary: ONTAPストレージシステムの導入と管理を自動化するためのオプションがいくつかあります。 
---
= ONTAP の自動化オプションを理解する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPストレージシステムの導入と管理を自動化するためのオプションがいくつかあります。



== ONTAP REST API

ONTAP 9.6 以降、 ONTAPには、ストレージ システムの導入と管理を自動化するための基盤を提供する強力な REST API が含まれています。それ以来、REST API は拡大と成熟を続けています。これにより、 ONTAP導入の管理を自動化する際に、優先的かつ戦略的なオプションが提供されるようになりました。

.REST APIへのネイティブアクセス
ONTAP REST API には、 REST クライアントをサポートする任意のプログラミング言語を使用して直接アクセスできます。代表的な言語の選択肢は、 Python 、 PowerShell 、 Java です。

.RESTを使用するための従来のONTAPIコードの移行
ONTAPI API (Zephyr API または ZAPI) は、データ ストレージ管理および管理タスクの自動化をサポートするためにNetApp ONTAPソフトウェアに含まれる独自の呼び出しのオリジナル セットです。  APIは、link:../sw-tools/learn-about-nmsdk.html["NetApp Manageability SDK の使用"] 。  ONTAPI API を使用する既存のコードがある場合は、REST API で利用できる拡張機能セットを活用するために、 ONTAP REST API への移行を計画する必要があります。 NetApp は、新しいONTAP REST API を使用するようにコードを変換するためのサポートを提供します。見るlink:../migrate/migration-considerations.html["ONTAPIからREST APIへの移行"]詳細についてはこちらをご覧ください。



== クライアントソフトウェアツールキット

NetAppには、ONTAP REST APIを抽象化し、自動化コードの作成を容易にするクライアントツールキットが用意されています。開発言語と環境に適したものを選択してください。

.Python クライアントライブラリ
Python クライアントライブラリは、 ONTAP REST API にアクセスするスクリプトを記述する際に使用できるパッケージです。接続管理、非同期要求処理、例外処理など、基盤となる複数のサービスをサポートします。Python クライアントライブラリを使用すると、 ONTAP の自動化目標をサポートする堅牢なコードを迅速に開発できます。詳細については、を参照してください link:../python/learn-about-pcl.html["Python クライアントライブラリ"] 。

.PowerShellツールキット
NetApp.ONTAP PowerShell Toolkitを使用すると、WindowsホストからのONTAPクラスタの管理を自動化できます。詳細については、を参照してください link:../pstk/learn-about-pstk.html["NetApp PowerShell Toolkitの詳細"] 。



== 自動化フレームワーク

いくつかのフレームワークのいずれかを使用して、自動化コードを作成して展開できます。

.Ansible
Ansible は、プロビジョニング、構成管理、アプリケーション導入をサポートするオープンソースのソフトウェアツールです。リリース以降、 RedHat が買収して以来、人気が高まってきています。ネットアップは、 Ansible 認定モジュールを提供しています。このモジュールを使用すると、 ONTAP ストレージシステムの管理を自動化できます。を参照してください link:../additional/learn_more.html["詳細はこちら。"] および https://www.netapp.com/devops-solutions/ansible/["ネットアップの Ansible DevOps ソリューション"^] 追加情報 の場合。

.BlueXP自動化カタログ
ネットアップ https://console.bluexp.netapp.com/automationCatalog/["BlueXP自動化カタログ"^] BlueXPのWebユーザインターフェイスから利用できます。このカタログでは、ONTAPの導入と他の製品との統合を自動化するのに役立つパッケージソリューションにアクセスできます。を参照してください https://docs.netapp.com/us-en/netapp-automation/["NetApp自動化"^] を参照してください。
