---
sidebar: sidebar 
permalink: rest/access_rest_api.html 
keywords:  
summary:  
---
= ONTAP API へのアクセス方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP REST API には、いくつかの方法でアクセスできます。



== ネットワークに関する考慮事項

REST API には、次のインターフェイスを通じて接続できます。

* クラスタ管理 LIF
* ノード管理 LIF
* SVM 管理 LIF


使用する LIF は、 HTTPS 管理プロトコルをサポートするように設定する必要があります。また、ネットワークのファイアウォール設定で HTTPS トラフィックを許可する必要があります。


TIP: 必ずクラスタ管理 LIF を使用してください。これにより、 API 要求の負荷がすべてのノードに分散され、オフラインになっているノードや接続の問題が発生しているノードは回避されます。



== ONTAP API オンラインドキュメントページ

ONTAP API オンラインドキュメントページに、 Web ブラウザを使用する際のアクセスポイントが記載されています。個々の API 呼び出しを直接実行する方法に加え、各呼び出しの入力パラメータやその他のオプションなど、 API の詳細な概要も含まれています。API 呼び出しは機能のカテゴリ別に分類されています。を参照してください link:../resources/overview_categories.html["REST リソースの概要"] を参照してください。

最新バージョンの API のドキュメントページにアクセスするための URL の形式は次のとおりです。

https://<cluster_mgmt_ip_address>/docs/api`



== カスタムのソフトウェアとツール

ONTAP API には、さまざまなプログラミング言語やツールを使用してアクセスできます。代表的なものとしては、 Python 、 Java 、 Curl 、 PowerShell などがあります。API を使用するプログラム、スクリプト、またはツールは、 REST Web サービスのクライアントとして機能します。プログラミング言語を使用すると、 API についての理解が深まり、 ONTAP の管理を自動化することもできます。

最新バージョンの API に直接アクセスするためのベース URL の形式は次のとおりです。

https://<cluster_mgmt_ip_address>/api`

複数のバージョンがサポートされている場合に特定のバージョンの API にアクセスするには、次の形式の URL を使用します。

https://<cluster_mgmt_ip_address>/api/v1`
