---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: operation, request and response, crud 
summary: ONTAP REST API には、いくつかの方法でアクセスできます。 
---
= 基本的な動作特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST で共通のテクノロジとベストプラクティスは確立されますが、各 API の詳細は設計内容に応じて異なる場合があります。



== 要求と応答の API トランザクション

すべての REST API 呼び出しは、 ONTAP システムへの HTTP 要求として実行され、クライアントへの関連する応答が生成されます。この要求と応答のペアで API トランザクションが構成されます。API を使用する前に、要求の制御に使用できる入力変数と応答出力の内容を理解しておく必要があります。



== CRUD 操作のサポート

ONTAP REST API で使用できる各リソースへのアクセスは CRUD モデルに基づきます。

* 作成
* 読み取り
* 更新
* 削除


一部のリソースでは、一部の処理のみがサポートされます。各リソースの詳細については、 ONTAP クラスタで ONTAP API ドキュメントページを参照してください。



== オブジェクト ID

各リソースインスタンスまたはオブジェクトには、作成時に一意の識別子が割り当てられます。ほとんどの場合、識別子は 128 ビットの UUID です。これらの識別子は、特定の ONTAP クラスタ内でグローバルに一意です。新しいオブジェクトインスタンスを作成する API 呼び出しを実行すると、関連付けられた ID の値を含む URL が HTTP 応答の場所ヘッダーにある呼び出し元に返されます。リソースインスタンスを以降の呼び出しで参照する際には、この識別子を抽出して使用できます。


NOTE: オブジェクト識別子の内容と内部構造は、いつでも変更される可能性があります。識別子を使用するのは、該当する API 呼び出しで関連付けられているオブジェクトを参照するときに必要に応じてのみです。



== オブジェクトのインスタンスとコレクション

リソースパスと HTTP メソッドに応じて、 API 呼び出しを特定のオブジェクトインスタンスまたはオブジェクトのコレクションに適用できます。



== 同期操作と非同期操作

ONTAP では、クライアントから受信した HTTP 要求を 2 つの方法で実行します。

同期処理:: ONTAP は要求をただちに実行し、成功した場合は HTTP ステータスコード 200 または 201 を返します。
+
--
GET 、 HEAD 、 OPTIONS の各メソッドを使用する要求は、いずれも常に同期的に実行されます。また、 POST 、 PATCH 、 DELETE を使用する要求は、完了までに 2 秒かからないと予想される場合は同期的に実行するように設計されています。

--
非同期処理:: 非同期要求が有効な場合、 ONTAP は要求を処理するバックグラウンドタスクと、タスクのアンカーを設定するジョブオブジェクトを作成します。HTTP ステータス 202 がジョブオブジェクトとともに呼び出し元に返されます。最終的な成功または失敗を確認するには、ジョブの状態を取得する必要があります。
+
--
POST 、 PATCH 、 DELETE の各メソッドを使用する要求は、完了までに 2 秒以上かかると予想される場合は非同期で実行するように設計されています。


NOTE: 。 `return_timeout` クエリパラメータは非同期API呼び出しで使用でき、非同期呼び出しを同期的に完了するように変換できます。を参照してください link:../rest/asynchronous_processing.html["ジョブオブジェクトを使用した非同期処理"] を参照してください。

--




== セキュリティ

REST API のセキュリティは、主に ONTAP で利用可能な既存のセキュリティ機能に基づいています。API で使用されるセキュリティは次のとおりです。

トランスポートレイヤのセキュリティ:: クライアントとONTAP LIFの間でネットワークを介して送信されるすべてのトラフィックは、ONTAP設定に基づいてTLSを使用して暗号化されます。
クライアント認証:: ONTAP System Manager および Network Manageability SDK と同じ認証オプションを ONTAP REST API でも使用できます。
HTTP 認証:: HTTPレベルでは、たとえばONTAP REST APIに直接アクセスする場合、次の2つの認証オプションがあります。いずれの場合も、HTTP認証ヘッダーを作成し、各要求に含める必要があります。
+
--
[cols="25,75"]
|===
| オプション | 説明 


| HTTPベーシック認証 | ONTAPのユーザ名とパスワードはコロンで連結されます。文字列はbase64に変換され、要求ヘッダーに含まれます。 


| OAuth 2.0 | ONTAP 9.14以降では、外部許可サーバからアクセストークンを要求し、それをベアラトークンとして要求ヘッダーに含めることができます。 
|===
OAuth 2.0の詳細と、OAuth 2.0がONTAPでどのように実装されているかについては、を参照してください。 https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["ONTAP OAuth 2.0実装の概要"^]。も参照してください link:../workflows/prepare_workflows.html["ワークフローを使用する準備をします"] このサイトで。

--
ONTAP 許可:: ONTAP では、ロールベースの認証モデルが実装されています。ONTAP REST API または API ドキュメントページにアクセスするときは、適切な権限を持つアカウントを使用する必要があります。

