---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: REST APIを使用してONTAP のEMS設定を管理できます。 
---
= ONTAP REST API を使用して EMS イベント通知を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP REST API を使用して、 Event Management System （ EMS ；イベント管理システム）の重要なイベント通知を送信する方法を設定したり、すべての EMS メッセージまたは特定の属性を持つ特定のメッセージを取得したりできます。REST API を使用すると、 EMS 関連のタスクを自動化し、 EMS メッセージを使用する他の方法に比べて時間を節約できます。

次の例は、 ONTAP REST API を使用して EMS メッセージを処理する方法を示しています。それぞれの例では、指定されている箇所で、情報の値を括弧で囲んで指定してください。サンプルを参照することもできます https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Python スクリプト"^] これは、いくつかの EMS 関連のアクティビティを自動化する方法を示しています。



== 特定のイベントログを表示します

「 get/support/ems/events 」 API 呼び出しを使用すると、最新のメッセージ、特定のテキストを含むメッセージ、特定の重大度を持つメッセージなど、特定のイベントメッセージを取得できます。

.要求例：最新のメッセージを取得します
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.応答例
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.要求例：特定のテキストと重大度を含むメッセージを取得する
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.応答例
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== 既存の EMS 設定を表示します

「 get/support/ems/」 API 呼び出しを使用すると、既存の EMS 通知設定に関する情報を取得できます。

.要求例
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.応答例
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== 新しい EMS 通知設定を作成します

複数の API 呼び出しを一緒に使用することで、新しい EMS 設定を作成してメッセージの受信方法と受信タイミングをカスタマイズできます。

.手順
. システム全体の E メール設定を行います。例：
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. 特定のルールを使用して特定のメッセージを照合するフィルタを定義します。例：
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. メッセージの宛先を作成します。例：
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== ONTAP REST API コマンドと ONTAP CLI コマンドの比較

ONTAP REST API を使用すると、多くのタスクで ONTAP CLI よりも少ないコマンドでワークフローを自動化できます。たとえば、複数の CLI コマンドを使用する代わりに、単一の POST API メソッドを使用してフィルタを作成できます。次の表に、一般的な EMS タスクと対応する REST API 呼び出しを完了するために必要な CLI コマンドを示します。

|===
| ONTAP REST API | ONTAP CLI 


| 「 get/support/ems 」を参照してください | event config show 


| 「 POST/support/ems/destinations 」  a| 
. イベント通知の送信先を作成します
. イベント通知は ''' を作成します




| 「 get/support/ems/events 」 | 「 event log show 」を参照してください 


| 「 POST/support/ems/filters 」と入力します  a| 
. 'event filter create -filter-name <filtername>`
. 'event filter rule add-filter-name <filtername>`


|===


== 関連情報

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["ONTAP REST API EMS サンプルの Python スクリプト"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["ONTAP REST API ：重大度の高いイベントの通知を自動化します"^]

